"""
Django settings for dbmonitor project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================================
# 环境分层配置（新增）
# ============================================================================
# 环境选项: dev / test / prod
ENVIRONMENT = os.environ.get('DJANGO_ENV', 'dev')

# ============================================================================
# 安全配置
# ============================================================================
# 生产环境必须通过环境变量设置 DJANGO_SECRET_KEY，不提供不安全的回退值
_SECRET_KEY_FALLBACK = 'django-insecure-change-me-in-production'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if ENVIRONMENT == 'prod':
        raise ValueError("生产环境必须配置 DJANGO_SECRET_KEY 环境变量")
    else:
        SECRET_KEY = _SECRET_KEY_FALLBACK

# DEBUG 模式控制
if ENVIRONMENT == 'prod':
    DEBUG = False
elif ENVIRONMENT == 'test':
    DEBUG = False
else:
    DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')

# 允许的主机
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,web,frontend').split(',')

# CSRF 信任来源
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', 'http://localhost:8000,http://127.0.0.1:8000').split(',')
    if o.strip()
]

# 安全中间件配置
if not DEBUG:
    SECURE_SSL_REDIRECT = (ENVIRONMENT == 'prod')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# Admin IP 白名单（新增）
ADMIN_IP_WHITELIST = [
    ip.strip()
    for ip in os.environ.get('ADMIN_IP_WHITELIST', '').split(',')
    if ip.strip()
]
# 如果配置了白名单，则启用 IP 检查
ADMIN_IP_WHITELIST_ENABLED = bool(ADMIN_IP_WHITELIST)

# 密码加密密钥（新增）
DB_MONITOR_SECRET_KEY = os.environ.get('DB_MONITOR_SECRET_KEY', '')
if not DB_MONITOR_SECRET_KEY:
    if ENVIRONMENT == 'prod':
        raise ValueError("生产环境必须配置 DB_MONITOR_SECRET_KEY 环境变量")
    else:
        # 开发环境使用默认密钥（仅用于开发）
        DB_MONITOR_SECRET_KEY = 'dev-only-secret-key-not-for-production'


# Application definition

INSTALLED_APPS = [
    'monitor',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 统一异常处理：将未捕获异常转为 JSON 响应
    'monitor.middleware.ExceptionMiddleware',
    # 操作审计：拦截写操作并记录到 AuditLog
    'monitor.middleware.AuditLogMiddleware',
]

ROOT_URLCONF = 'dbmonitor.urls'

# 前端已迁移至 React SPA，Django 模板引擎仅保留以兼容 Django Admin
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,  # Django Admin 仍需要模板引擎
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dbmonitor.wsgi.application'


# ============================================================================
# 数据库配置
# ============================================================================
# 配置数据存储：PostgreSQL（Docker TimescaleDB 容器）
# 采集指标数据存储：Elasticsearch
USE_POSTGRESQL = os.environ.get('USE_POSTGRESQL', 'True').lower() in ('true', '1', 'yes')

if not USE_POSTGRESQL:
    raise RuntimeError(
        "SQLite 已弃用，DB-AIOps 平台必须使用 PostgreSQL。"
        "请设置 USE_POSTGRESQL=True 并确保 PostgreSQL/TimescaleDB 可用。"
    )

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', 'db_monitor'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'postgres123'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        'CONN_MAX_AGE': 60,  # 持久连接 1 分钟（开发环境，避免连接池耗尽）
        'OPTIONS': {
            'connect_timeout': 10,
            'application_name': 'db_monitor',
        },
    }
}

# Elasticsearch 配置（采集指标存储）
ES_ENABLED = os.environ.get('ES_ENABLED', 'True').lower() in ('true', '1', 'yes')
ES_HOST = os.environ.get('ES_HOST', 'localhost')
ES_PORT = int(os.environ.get('ES_PORT', '9200'))
ES_URL = os.environ.get('ES_URL', f'http://{ES_HOST}:{ES_PORT}')

# TimescaleDB 配置（监控指标时序存储）
TIMESCALEDB_ENABLED = os.environ.get('TIMESCALEDB_ENABLED', 'True').lower() in ('true', '1', 'yes')

# TimescaleDB 连接配置（Docker TimescaleDB 容器）
TIMESCALEDB_HOST = os.environ.get('TIMESCALEDB_HOST', 'localhost')
TIMESCALEDB_PORT = os.environ.get('TIMESCALEDB_PORT', '5432')
TIMESCALEDB_NAME = os.environ.get('TIMESCALEDB_NAME', 'timeseriesdb')
TIMESCALEDB_USER = os.environ.get('TIMESCALEDB_USER', 'postgres')
TIMESCALEDB_PASSWORD = os.environ.get('TIMESCALEDB_PASSWORD', 'postgres123')

# TimescaleDB 时序数据保留策略
TIMESCALEDB_RETENTION_DAYS = int(os.environ.get('TIMESCALEDB_RETENTION_DAYS', '90'))
TIMESCALEDB_COMPRESSION_INTERVAL = os.environ.get('TIMESCALEDB_COMPRESSION_INTERVAL', '7 days')


# ============================================================================
# 缓存配置
# ============================================================================
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
# 生产环境（gunicorn 多 worker）必须使用 Redis 缓存，否则 Token 认证无法跨 worker 共享
if ENVIRONMENT in ('prod', 'test'):
    USE_REDIS_CACHE = True
else:
    USE_REDIS_CACHE = os.environ.get('USE_REDIS_CACHE', 'False').lower() in ('true', '1', 'yes')

if USE_REDIS_CACHE:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'TIMEOUT': 300,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'dbmonitor-local',
        }
    }


# ============================================================================
# Celery 配置（预留）
# ============================================================================
USE_CELERY = os.environ.get('USE_CELERY', 'False').lower() in ('true', '1', 'yes')

if USE_CELERY:
    CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/1')
    CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/2')
    CELERY_ACCEPT_CONTENT = ['json']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_SERIALIZER = 'json'
    CELERY_TIMEZONE = 'Asia/Shanghai'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# 静态文件收集目录
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 额外静态文件目录
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'frontend', 'dist'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==========================================
# 邮件发送配置
# ==========================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# SMTP服务器地址 (例如: smtp.qq.com, smtp.163.com, smtp.office365.com)
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.qq.com')

# SMTP端口 (通常是 465 或 587)
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '465'))

# 发件人邮箱账号
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')

# 邮箱密码 (注意：如果是QQ/网易，这里填的是"授权码"，不是登录密码)
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# 是否使用 SSL 安全连接 (465端口通常选True)
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'True').lower() in ('true', '1', 'yes')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'False').lower() in ('true', '1', 'yes')

# 默认发件人 (格式: "显示名字 <邮箱地址>")
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', f"DB监控系统 <{EMAIL_HOST_USER}>")

# 接收告警的邮箱列表
ADMIN_EMAILS = [
    x.strip()
    for x in os.environ.get('ADMIN_EMAILS', EMAIL_HOST_USER).split(',')
    if x.strip()
]

# ==========================================
# 钉钉机器人告警配置
# ==========================================
DINGTALK_WEBHOOK = os.environ.get('DINGTALK_WEBHOOK', '')
DINGTALK_SECRET = os.environ.get('DINGTALK_SECRET', '')

# ==========================================
# 企业微信机器人告警配置（新增）
# ==========================================
WECOM_WEBHOOK = os.environ.get('WECOM_WEBHOOK', '')
WECOM_AGENT_ID = os.environ.get('WECOM_AGENT_ID', '')

# 已在文件开头定义，此处避免重复赋值
# DB_MONITOR_SECRET_KEY = os.environ.get('DB_MONITOR_SECRET_KEY', '')

# ==========================================
# 采集调度参数
# ==========================================
# 单个数据库采集超时（秒）
COLLECT_TIMEOUT_SEC = int(os.environ.get('COLLECT_TIMEOUT_SEC', 60))
# 并发采集线程数
COLLECT_WORKERS = int(os.environ.get('COLLECT_WORKERS', 20))
# 采集间隔（秒）
COLLECT_INTERVAL_SEC = int(os.environ.get('COLLECT_INTERVAL_SEC', 60))

# ==========================================
# Phase 2 智能引擎开关
# ==========================================
ENABLE_PHASE2_ENGINES = os.environ.get('ENABLE_PHASE2_ENGINES', 'True').lower() in ('true', '1', 'yes')
# 容量预测检查间隔（小时）
CAPACITY_CHECK_INTERVAL_HOURS = int(os.environ.get('CAPACITY_CHECK_INTERVAL_HOURS', 24))
# 健康评分检查间隔（小时）
HEALTH_CHECK_INTERVAL_HOURS = int(os.environ.get('HEALTH_CHECK_INTERVAL_HOURS', 1))

# ==========================================
# API 配置
# ==========================================
API_RATE_LIMIT = int(os.environ.get('API_RATE_LIMIT', 100))  # 每分钟请求数限制
API_TOKEN_EXPIRY_HOURS = int(os.environ.get('API_TOKEN_EXPIRY_HOURS', 24))  # Token 过期时间

# ============================================================================
# 日志配置
# ============================================================================
LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'db_monitor.log'),
            'maxBytes': 50 * 1024 * 1024,  # 50MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_DIR, 'error.log'),
            'maxBytes': 50 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'monitor': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
