"""
Django settings for dbmonitor project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v(j06=*3x3&c6c6w$+0fi8fo-jpnas#ko6+@gi&b(v_a=kw4xu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Django 4+ CSRF 需要明确信任的来源列表（本地开发）
CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:8000', 'http://localhost:8000']


# Application definition

INSTALLED_APPS = [
    'monitor', # <--- 这是我们需要新增的一行
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dbmonitor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dbmonitor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==========================================
# 邮件发送配置
# ==========================================
# 邮件后端 (默认不用动)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# SMTP服务器地址 (例如: smtp.qq.com, smtp.163.com, smtp.office365.com)
EMAIL_HOST = 'smtp.qq.com' 

# SMTP端口 (通常是 465 或 587，如果是 25 请把下面两个 False 改一下)
EMAIL_PORT = 465 

# 发件人邮箱账号
EMAIL_HOST_USER = 'smudy@qq.com' 

# 邮箱密码 (注意：如果是QQ/网易，这里填的是"授权码"，不是登录密码！如果是公司邮箱则是密码)
EMAIL_HOST_PASSWORD = 'qkygyyjtofaubhbj' 

# 是否使用 SSL 安全连接 (465端口通常选True)
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False

# 默认发件人 (格式: "显示名字 <邮箱地址>")
DEFAULT_FROM_EMAIL = f"DB监控系统 <{EMAIL_HOST_USER}>"

# 接收告警的邮箱列表 (可以是同一个邮箱)
ADMIN_EMAILS = ['smudy@qq.com']

# ==========================================
# 钉钉机器人告警配置（v0.1.0 新增）
# ==========================================
# 钉钉自定义机器人 Webhook URL（留空则禁用钉钉通知）
DINGTALK_WEBHOOK = ''
# 钉钉加签密钥（在机器人配置页面开启"加签"后填入，不填则不签名）
DINGTALK_SECRET = ''

# ==========================================
# 密码加密密钥（v0.1.0 新增）
# ==========================================
# 用于 AES-256-GCM 加密数据库连接密码
# 生产环境请通过环境变量 DB_MONITOR_SECRET_KEY 注入，不要写在此文件中
# DB_MONITOR_SECRET_KEY = 'your-32-char-secret-key'

# ==========================================
# 采集调度参数（v0.1.0 新增）
# ==========================================
# 单个数据库采集超时（秒），超过后记录 DOWN，不阻塞其他库
COLLECT_TIMEOUT_SEC = 15
# 并发采集线程数（建议不超过数据库实例数）
COLLECT_WORKERS = 20