# Generated by Django 5.2.8 on 2025-11-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如: 核心交易库_主节点', max_length=100, verbose_name='连接别名')),
                ('db_type', models.CharField(choices=[('oracle', 'Oracle'), ('mysql', 'MySQL'), ('redis', 'Redis'), ('pgsql', 'PostgreSQL'), ('mongo', 'MongoDB'), ('dm', '达梦数据库'), ('gbase', 'Gbase 8a')], max_length=20, verbose_name='数据库类型')),
                ('host', models.CharField(max_length=100, verbose_name='IP地址')),
                ('port', models.IntegerField(verbose_name='端口号')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否开启监控')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '数据库配置',
                'verbose_name_plural': '数据库配置列表',
            },
        ),
    ]
