# Generated by Django 5.2.8 on 2025-11-28 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='UP', max_length=10, verbose_name='状态')),
                ('message', models.TextField(verbose_name='监控数据/报错信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='巡检时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.databaseconfig', verbose_name='数据库')),
            ],
            options={
                'verbose_name': '监控日志',
                'verbose_name_plural': '监控日志列表',
            },
        ),
    ]
