# Generated by Django 5.2.8 on 2025-12-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_monitorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconfig',
            name='service_name',
            field=models.CharField(blank=True, help_text='Oracle必填服务名，其他库可留空', max_length=100, null=True, verbose_name='服务名/SID'),
        ),
    ]
