# Generated by Django 6.0.3 on 2026-04-09 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_databaseconfig_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconfig',
            name='db_type',
            field=models.CharField(choices=[('oracle', 'Oracle'), ('mysql', 'MySQL'), ('redis', 'Redis'), ('pgsql', 'PostgreSQL'), ('mongo', 'MongoDB'), ('dm', '达梦数据库'), ('gbase', 'Gbase 8a'), ('tdsql', 'TDSQL')], max_length=20, verbose_name='数据库类型'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('KILL_SESSION', '终止会话'), ('RESIZE_DATAFILE', '扩容数据文件'), ('ADD_DATAFILE', '添加数据文件'), ('DROP_INDEX', '删除索引'), ('PURGE_TABLE', '清理表数据'), ('REBALANCE_SHARD', '分片重平衡'), ('EXECUTE_SQL', '执行自定义 SQL')], max_length=50, verbose_name='操作类型')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('sql_command', models.TextField(verbose_name='SQL 命令')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险'), ('critical', '极高风险')], default='medium', max_length=20, verbose_name='风险等级')),
                ('rollback_command', models.TextField(blank=True, null=True, verbose_name='回滚命令')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('approved', '已批准'), ('executing', '执行中'), ('success', '执行成功'), ('failed', '执行失败'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('approver', models.CharField(blank=True, max_length=100, null=True, verbose_name='审批人')),
                ('approve_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('executor', models.CharField(blank=True, max_length=100, null=True, verbose_name='执行人')),
                ('execute_time', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('execution_result', models.TextField(blank=True, null=True, verbose_name='执行结果')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.databaseconfig', verbose_name='数据库')),
                ('related_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.monitorlog', verbose_name='关联监控日志')),
            ],
            options={
                'verbose_name': '运维操作审计',
                'verbose_name_plural': '运维操作审计列表',
                'ordering': ['-create_time'],
            },
        ),
    ]
