# Generated by Django 6.0.3 on 2026-04-16 00:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_alter_databaseconfig_db_type_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconfig',
            name='password',
            field=models.CharField(max_length=512, verbose_name='密码'),
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('down', '实例 DOWN/UP'), ('tablespace', '表空间容量'), ('connection', '连接数使用率'), ('lock', '锁等待'), ('baseline', '基线偏离')], max_length=50, verbose_name='告警类型')),
                ('metric_key', models.CharField(blank=True, default='', max_length=100, verbose_name='指标键')),
                ('severity', models.CharField(default='warning', max_length=20, verbose_name='严重程度')),
                ('title', models.CharField(max_length=200, verbose_name='告警标题')),
                ('description', models.TextField(verbose_name='告警详情')),
                ('status', models.CharField(choices=[('active', '活跃'), ('resolved', '已恢复')], default='active', max_length=20, verbose_name='状态')),
                ('last_notified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后通知时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='恢复时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='首次告警时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.databaseconfig', verbose_name='数据库')),
            ],
            options={
                'verbose_name': '告警日志',
                'verbose_name_plural': '告警日志列表',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['config', 'alert_type', 'metric_key', 'status'], name='monitor_ale_config__438e96_idx')],
            },
        ),
    ]
