# Generated by Django 6.0.4 on 2026-04-22 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_alter_databaseconfig_password_alertlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='related_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.auditlog', verbose_name='关联工单'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='execution_context',
            field=models.JSONField(blank=True, null=True, verbose_name='执行上下文'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='execution_evidence',
            field=models.JSONField(blank=True, null=True, verbose_name='执行证据'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='triggered_by_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.alertlog', verbose_name='触发告警'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '管理员'), ('supervisor', 'Supervisor'), ('user', '普通用户'), ('readonly', '只读用户')], default='user', max_length=20, verbose_name='角色')),
                ('allowed_databases', models.JSONField(blank=True, help_text='为空表示可访问所有数据库，列表形式指定可访问的数据库ID', null=True, verbose_name='可访问数据库列表')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户配置',
                'verbose_name_plural': '用户配置列表',
            },
        ),
    ]
