# Generated by Django 6.0.4 on 2026-04-29 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_alertlog_related_ticket_auditlog_execution_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('metric_key', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='指标键')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('unit', models.CharField(blank=True, help_text='count/pct/mb/qps/sec', max_length=20, null=True, verbose_name='单位')),
                ('db_types', models.JSONField(blank=True, help_text="如 ['oracle','mysql']，为空表示全部", null=True, verbose_name='适用数据库类型')),
                ('alert_direction', models.CharField(choices=[('up', '上升敏感'), ('down', '下降敏感'), ('both', '双向敏感')], default='up', max_length=10, verbose_name='告警方向')),
                ('sigma_k', models.FloatField(default=2.0, help_text='正常范围 = mean ± k*std', verbose_name='Sigma倍数')),
                ('fixed_warn_val', models.FloatField(blank=True, help_text='基线未就绪时使用', null=True, verbose_name='固定阈值兜底')),
                ('is_capacity', models.BooleanField(default=False, help_text='是否参与容量预测', verbose_name='是否容量指标')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '指标定义',
                'verbose_name_plural': '指标定义列表',
            },
        ),
        migrations.CreateModel(
            name='AlertNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', '邮件'), ('dingtalk', '钉钉'), ('wecom', '企业微信'), ('sms', '短信')], max_length=20, verbose_name='通知渠道')),
                ('status', models.CharField(choices=[('success', '发送成功'), ('failed', '发送失败'), ('skipped', '跳过')], max_length=20, verbose_name='发送状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='monitor.alertlog', verbose_name='告警')),
            ],
            options={
                'verbose_name': '告警通知日志',
                'verbose_name_plural': '告警通知日志列表',
                'ordering': ['-send_time'],
            },
        ),
        migrations.CreateModel(
            name='AlertSilenceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='静默窗口名称')),
                ('alert_type', models.CharField(blank=True, default='', help_text='为空表示所有类型', max_length=50, verbose_name='告警类型')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('weekdays', models.CharField(default='1,2,3,4,5,6,7', help_text='逗号分隔，1=周一,7=周日', max_length=20, verbose_name='星期几')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='精确开始时间')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='精确结束时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='静默原因')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('config', models.ForeignKey(blank=True, help_text='为空表示全局静默', null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.databaseconfig', verbose_name='数据库')),
            ],
            options={
                'verbose_name': '告警静默窗口',
                'verbose_name_plural': '告警静默窗口列表',
            },
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField(verbose_name='步骤顺序')),
                ('approver', models.CharField(max_length=100, verbose_name='审批人')),
                ('approver_role', models.CharField(max_length=50, verbose_name='审批角色')),
                ('action', models.CharField(choices=[('approve', '批准'), ('reject', '拒绝'), ('comment', '评论')], max_length=20, verbose_name='审批动作')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='审批意见')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='审批时间')),
                ('audit_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='monitor.auditlog', verbose_name='工单')),
            ],
            options={
                'verbose_name': '审批记录',
                'verbose_name_plural': '审批记录列表',
                'ordering': ['audit_log', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险'), ('critical', '极高风险')], max_length=20, verbose_name='风险等级')),
                ('step_order', models.IntegerField(help_text='从1开始', verbose_name='步骤顺序')),
                ('approver_role', models.CharField(help_text='如 admin, supervisor', max_length=50, verbose_name='审批角色')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='步骤描述')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必须')),
            ],
            options={
                'verbose_name': '审批步骤',
                'verbose_name_plural': '审批步骤列表',
                'ordering': ['risk_level', 'step_order'],
                'unique_together': {('risk_level', 'step_order')},
            },
        ),
        migrations.CreateModel(
            name='BusinessSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='业务系统名称')),
                ('importance', models.CharField(choices=[('critical', '核心'), ('important', '重要'), ('normal', '一般')], default='normal', max_length=20, verbose_name='重要程度')),
                ('owner', models.CharField(blank=True, max_length=100, null=True, verbose_name='负责人')),
                ('contact', models.CharField(blank=True, max_length=200, null=True, verbose_name='联系方式')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('databases', models.ManyToManyField(blank=True, related_name='business_systems', to='monitor.databaseconfig', verbose_name='关联数据库')),
            ],
            options={
                'verbose_name': '业务系统',
                'verbose_name_plural': '业务系统列表',
            },
        ),
        migrations.CreateModel(
            name='PlatformMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='指标名称')),
                ('metric_type', models.CharField(choices=[('counter', '计数器'), ('gauge', '仪表盘'), ('histogram', '直方图')], max_length=20, verbose_name='指标类型')),
                ('value', models.FloatField(verbose_name='当前值')),
                ('labels', models.JSONField(blank=True, null=True, verbose_name='标签')),
                ('help_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='说明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '平台指标',
                'verbose_name_plural': '平台指标列表',
                'unique_together': {('name', 'labels')},
            },
        ),
        migrations.CreateModel(
            name='BaselineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(max_length=100, verbose_name='指标键')),
                ('time_slot', models.IntegerField(help_text='0-167（星期几×24 + 小时）', verbose_name='时间槽')),
                ('sample_count', models.IntegerField(default=0, verbose_name='样本数')),
                ('mean', models.FloatField(default=0.0, verbose_name='均值')),
                ('std', models.FloatField(default=0.0, verbose_name='标准差')),
                ('p90', models.FloatField(default=0.0, verbose_name='P90')),
                ('p95', models.FloatField(default=0.0, verbose_name='P95')),
                ('p99', models.FloatField(default=0.0, verbose_name='P99')),
                ('normal_min', models.FloatField(default=0.0, verbose_name='正常下限')),
                ('normal_max', models.FloatField(default=0.0, verbose_name='正常上限')),
                ('data_sufficient', models.BooleanField(default=False, verbose_name='数据充分')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.databaseconfig', verbose_name='数据库')),
            ],
            options={
                'verbose_name': '基线模型',
                'verbose_name_plural': '基线模型列表',
                'indexes': [models.Index(fields=['config', 'metric_key', 'time_slot'], name='monitor_bas_config__da5dac_idx')],
                'unique_together': {('config', 'metric_key', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='HealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_date', models.DateField(verbose_name='评分日期')),
                ('total_score', models.FloatField(help_text='0-100', verbose_name='总分')),
                ('availability_score', models.FloatField(default=0.0, verbose_name='可用性得分')),
                ('capacity_score', models.FloatField(default=0.0, verbose_name='容量得分')),
                ('performance_score', models.FloatField(default=0.0, verbose_name='性能得分')),
                ('config_score', models.FloatField(default=0.0, verbose_name='配置得分')),
                ('ops_score', models.FloatField(default=0.0, verbose_name='运维得分')),
                ('grade', models.CharField(blank=True, max_length=5, null=True, verbose_name='等级')),
                ('score_detail', models.JSONField(blank=True, null=True, verbose_name='评分详情')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.databaseconfig', verbose_name='数据库')),
            ],
            options={
                'verbose_name': '健康评分',
                'verbose_name_plural': '健康评分列表',
                'ordering': ['-score_date'],
                'unique_together': {('config', 'score_date')},
            },
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(max_length=100, verbose_name='指标键')),
                ('resource_name', models.CharField(blank=True, help_text='如表空间名', max_length=100, null=True, verbose_name='资源名称')),
                ('current_value', models.FloatField(blank=True, null=True, verbose_name='当前值')),
                ('monthly_growth_rate', models.FloatField(blank=True, null=True, verbose_name='月增长率(%)')),
                ('predicted_warn_date', models.DateField(blank=True, null=True, verbose_name='预计触达告警线日期')),
                ('predicted_crit_date', models.DateField(blank=True, null=True, verbose_name='预计触达危险线日期')),
                ('model_used', models.CharField(blank=True, max_length=50, null=True, verbose_name='使用的模型')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='置信度')),
                ('recommendation', models.TextField(blank=True, null=True, verbose_name='建议')),
                ('generated_at', models.DateTimeField(auto_now=True, verbose_name='生成时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.databaseconfig', verbose_name='数据库')),
            ],
            options={
                'verbose_name': '容量预测结果',
                'verbose_name_plural': '容量预测结果列表',
                'unique_together': {('config', 'metric_key', 'resource_name')},
            },
        ),
    ]
