# Generated by Django 6.0.4 on 2026-05-07 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_alertthresholdtemplate_databasealertoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：生产库-严格、测试库-宽松', max_length=100, verbose_name='模板名称')),
                ('db_type', models.CharField(choices=[('oracle', 'Oracle'), ('mysql', 'MySQL'), ('redis', 'Redis'), ('pgsql', 'PostgreSQL'), ('mongo', 'MongoDB'), ('dm', '达梦数据库'), ('gbase', 'Gbase 8a'), ('tdsql', 'TDSQL')], max_length=20, verbose_name='数据库类型')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为默认模板')),
                ('description', models.TextField(blank=True, null=True, verbose_name='模板描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '告警模板组',
                'verbose_name_plural': '告警模板组列表',
                'ordering': ['db_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseTemplateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '数据库模板分配',
                'verbose_name_plural': '数据库模板分配列表',
            },
        ),
        migrations.AlterModelOptions(
            name='alertthresholdtemplate',
            options={'ordering': ['template', 'metric_key'], 'verbose_name': '告警阈值规则', 'verbose_name_plural': '告警阈值规则列表'},
        ),
        migrations.RemoveConstraint(
            model_name='alertthresholdtemplate',
            name='unique_template_db_metric',
        ),
        migrations.RemoveConstraint(
            model_name='databasealertoverride',
            name='unique_override_db_metric',
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='status',
            field=models.CharField(choices=[('active', '活跃'), ('acknowledged', '已确认'), ('resolved', '已恢复')], default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterUniqueTogether(
            name='databasealertoverride',
            unique_together={('db_config', 'metric_key')},
        ),
        migrations.AlterUniqueTogether(
            name='alerttemplate',
            unique_together={('name', 'db_type')},
        ),
        migrations.AddField(
            model_name='alertthresholdtemplate',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='monitor.alerttemplate', verbose_name='所属模板组'),
        ),
        migrations.AlterUniqueTogether(
            name='alertthresholdtemplate',
            unique_together={('template', 'metric_key')},
        ),
        migrations.AddField(
            model_name='databasetemplateassignment',
            name='db_config',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_assignment', to='monitor.databaseconfig', verbose_name='数据库'),
        ),
        migrations.AddField(
            model_name='databasetemplateassignment',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_databases', to='monitor.alerttemplate', verbose_name='使用的模板组'),
        ),
    ]
