# Generated by Django 6.0.4 on 2026-05-14 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_multi_template_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', '日报'), ('weekly', '周报'), ('monthly', '月报')], max_length=20, verbose_name='报表类型')),
                ('title', models.CharField(max_length=200, verbose_name='报表标题')),
                ('content_html', models.TextField(blank=True, default='', verbose_name='HTML内容')),
                ('file_path', models.CharField(blank=True, default='', max_length=500, verbose_name='文件路径')),
                ('period_start', models.DateField(verbose_name='统计周期开始')),
                ('period_end', models.DateField(verbose_name='统计周期结束')),
                ('recipients', models.JSONField(default=list, verbose_name='收件人列表')),
                ('status', models.CharField(choices=[('generated', '已生成'), ('sent', '已发送'), ('failed', '发送失败')], default='generated', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '报表记录',
                'verbose_name_plural': '报表记录列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseTopology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', '主库'), ('standby', '备库'), ('rac_node', 'RAC节点'), ('dsc_node', 'DSC节点'), ('single', '单机')], default='single', max_length=20, verbose_name='角色')),
                ('topology_type', models.CharField(choices=[('primary_standby', '主从'), ('rac', 'RAC'), ('adg', 'Active Data Guard'), ('mha', 'MHA'), ('dsc', 'DSC集群'), ('dts', 'DTS复制'), ('single', '单机')], default='single', max_length=20, verbose_name='拓扑类型')),
                ('cluster_name', models.CharField(blank=True, default='', max_length=100, verbose_name='集群名称')),
                ('sync_mode', models.CharField(blank=True, choices=[('sync', '同步'), ('async', '异步'), ('semi_sync', '半同步'), ('', '未知')], default='', max_length=20, verbose_name='同步模式')),
                ('lag_seconds', models.FloatField(blank=True, null=True, verbose_name='延迟秒数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('db_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topology_info', to='monitor.databaseconfig', verbose_name='数据库')),
                ('peer_databases', models.ManyToManyField(blank=True, related_name='peer_topologies', to='monitor.databaseconfig', verbose_name='关联数据库')),
            ],
            options={
                'verbose_name': '数据库拓扑',
                'verbose_name_plural': '数据库拓扑列表',
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('alert_types', models.JSONField(default=list, help_text="匹配的告警类型列表，如 ['down','tablespace']，为空表示全部", verbose_name='告警类型')),
                ('severities', models.JSONField(default=list, help_text="匹配的严重程度列表，如 ['critical','error']，为空表示全部", verbose_name='严重程度')),
                ('channels', models.JSONField(default=list, help_text="发送到哪些渠道，如 ['email','dingtalk','wecom']", verbose_name='通知渠道')),
                ('schedule', models.JSONField(blank=True, help_text="{'work_hours': true, 'start': '09:00', 'end': '18:00', 'weekdays': '1,2,3,4,5'}", null=True, verbose_name='时间策略')),
                ('escalation_minutes', models.IntegerField(default=0, help_text='0 表示不升级，>0 表示未确认 N 分钟后自动提升等级', verbose_name='升级等待时间(分钟)')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('priority', models.IntegerField(default=0, help_text='数字越大优先级越高，同告警匹配多规则时取最高优先级', verbose_name='优先级')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('db_config', models.ForeignKey(blank=True, help_text='为空表示全局规则', null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.databaseconfig', verbose_name='数据库')),
            ],
            options={
                'verbose_name': '通知规则',
                'verbose_name_plural': '通知规则列表',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
