# Generated by Django 6.0.4 on 2026-05-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_reportrecord_databasetopology_notificationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconfig',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='密码最后修改时间'),
        ),
        migrations.AddField(
            model_name='databaseconfig',
            name='password_expiry_days',
            field=models.IntegerField(default=90, help_text='默认90天，0表示不过期', verbose_name='密码过期天数'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('KILL_SESSION', '终止会话'), ('RESIZE_DATAFILE', '扩容数据文件'), ('ADD_DATAFILE', '添加数据文件'), ('DROP_INDEX', '删除索引'), ('PURGE_TABLE', '清理表数据'), ('REBALANCE_SHARD', '分片重平衡'), ('EXECUTE_SQL', '执行自定义 SQL'), ('API_CREATE', 'API 创建'), ('API_UPDATE', 'API 更新'), ('API_DELETE', 'API 删除')], max_length=50, verbose_name='操作类型'),
        ),
    ]
