# Generated by Django 6.0.5 on 2026-05-25 04:27

import django.db.models.deletion
from django.db import migrations, models


# 旧角色字符串到新角色编码的映射
ROLE_MIGRATION_MAP = {
    'admin': 'super_admin',
    'supervisor': 'dba',
    'user': 'config_operator',
    'readonly': 'readonly',
    # auth.py 旧常量映射
    'read_only_observer': 'readonly',
    'dba_operator': 'dba',
    'dba_supervisor': 'dba',
}

# 内置角色定义
BUILTIN_ROLES = [
    ('super_admin', '超级管理员', '拥有所有权限，可管理用户和角色，不可删除', True),
    ('dba', '数据库管理员', '数据库运维操作、告警确认、工单审批、配置管理', True),
    ('auditor', '审计用户', '只读查看所有数据、查看审计日志和报表，不能修改', True),
    ('config_operator', '配置用户', '可管理数据库配置、告警配置、通知规则，不能执行运维操作', True),
    ('readonly', '只读用户', '仅查看仪表盘和基础监控数据', True),
]


def create_roles_and_migrate_data(apps, schema_editor):
    """数据迁移：创建内置角色，迁移 UserProfile.role 字段"""
    Role = apps.get_model('monitor', 'Role')
    UserProfile = apps.get_model('monitor', 'UserProfile')

    # 1. 创建5个内置角色
    role_map = {}
    for code, name, desc, is_builtin in BUILTIN_ROLES:
        role, _ = Role.objects.get_or_create(
            code=code,
            defaults={'name': name, 'description': desc, 'is_builtin': is_builtin}
        )
        role_map[code] = role

    # 2. 迁移 UserProfile 的旧 role 字符串值到新的 FK
    for profile in UserProfile.objects.all():
        old_role = profile.role_id  # 此时已经是 FK，但旧数据可能是 None
        if old_role is None:
            # 尝试从原来的 role 字段值映射
            # 由于 AlterField 已经执行，旧的字符串值已丢失
            # 默认分配 readonly 角色
            profile.role = role_map.get('readonly')
            profile.save(update_fields=['role'])


def reverse_migrate(apps, schema_editor):
    """反向迁移：删除自定义角色（保留内置角色的权限数据）"""
    Role = apps.get_model('monitor', 'Role')
    # 先清空 UserProfile 的 FK
    UserProfile = apps.get_model('monitor', 'UserProfile')
    UserProfile.objects.update(role=None)
    # 删除所有角色
    Role.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_databaseconfig_password_changed_at_and_more'),
    ]

    operations = [
        # Step 1: 创建 Role 表
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='如 super_admin, dba, auditor', max_length=50, unique=True, verbose_name='角色编码')),
                ('name', models.CharField(help_text='如 超级管理员, 数据库管理员', max_length=100, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='角色描述')),
                ('is_builtin', models.BooleanField(default=False, help_text='内置角色不可删除', verbose_name='是否内置角色')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色列表',
                'ordering': ['is_builtin', 'code'],
            },
        ),

        # Step 2: 先把 UserProfile.role 从 CharField 改为 CharField(max_length=50) 做过渡
        #         同时添加一个临时的 _old_role 字段保存旧值
        migrations.AddField(
            model_name='userprofile',
            name='_old_role',
            field=models.CharField(max_length=50, null=True, blank=True, verbose_name='旧角色'),
        ),

        # Step 3: 迁移旧角色数据到 _old_role 字段
        migrations.RunPython(
            code=lambda apps, schema_editor: _save_old_roles(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),

        # Step 4: 创建内置角色
        migrations.RunPython(
            code=create_roles_and_migrate_data,
            reverse_code=reverse_migrate,
        ),

        # Step 5: 将 UserProfile.role 从 CharField 改为 FK
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='monitor.role', verbose_name='角色'),
        ),

        # Step 6: 根据 _old_role 设置新的 FK
        migrations.RunPython(
            code=lambda apps, schema_editor: _migrate_role_fk(apps, schema_editor),
            reverse_code=migrations.RunPython.noop,
        ),

        # Step 7: 删除临时字段
        migrations.RemoveField(
            model_name='userprofile',
            name='_old_role',
        ),

        # Step 8: 创建 RolePermission 表
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(help_text='格式: module.action，如 databases.view', max_length=100, verbose_name='权限编码')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='monitor.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色权限',
                'verbose_name_plural': '角色权限列表',
                'indexes': [models.Index(fields=['permission_code'], name='monitor_rol_permiss_7a0333_idx')],
                'unique_together': {('role', 'permission_code')},
            },
        ),
    ]


def _save_old_roles(apps, schema_editor):
    """保存旧的 role 字符串值到 _old_role 字段"""
    UserProfile = apps.get_model('monitor', 'UserProfile')
    # 使用 raw SQL 读取旧 role 值并写入 _old_role
    from django.db import connection
    with connection.cursor() as cursor:
        cursor.execute('UPDATE monitor_userprofile SET _old_role = role')


def _migrate_role_fk(apps, schema_editor):
    """根据 _old_role 字段设置新的 FK"""
    Role = apps.get_model('monitor', 'Role')
    UserProfile = apps.get_model('monitor', 'UserProfile')

    role_map = {}
    for role in Role.objects.all():
        role_map[role.code] = role

    for profile in UserProfile.objects.all():
        old_role = profile._old_role or 'readonly'
        new_code = ROLE_MIGRATION_MAP.get(old_role, 'readonly')
        profile.role = role_map.get(new_code)
        profile.save(update_fields=['role'])
