# Generated by Django 6.0.5 on 2026-07-12 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_alertcase_businessimpactassessment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.CharField(db_index=True, max_length=48, unique=True, verbose_name='问题ID')),
                ('signature', models.CharField(db_index=True, max_length=200, verbose_name='归一签名')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('incident_count', models.IntegerField(default=0, verbose_name='累计事故数')),
                ('first_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='首次出现')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='最近出现')),
                ('kb_ref', models.CharField(blank=True, default='', max_length=64, verbose_name='知识库引用')),
                ('status', models.CharField(choices=[('active', '活跃'), ('mitigated', '已缓解'), ('archived', '已归档')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题列表',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(db_index=True, max_length=48, unique=True, verbose_name='事故ID')),
                ('db_type', models.CharField(max_length=20, verbose_name='数据库类型')),
                ('category', models.CharField(choices=[('availability', '可用性'), ('lock', '锁'), ('connection', '连接'), ('capacity', '容量'), ('replication', '复制'), ('performance', '性能'), ('config', '配置'), ('other', '其他')], db_index=True, max_length=20, verbose_name='类别')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('priority', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], db_index=True, max_length=4, verbose_name='优先级')),
                ('status', models.CharField(choices=[('open', '待处理'), ('diagnosing', '诊断中'), ('plan_ready', '方案就绪'), ('executing', '执行中'), ('verifying', '验证中'), ('resolved', '已解决'), ('closed', '已关闭')], db_index=True, default='open', max_length=20, verbose_name='状态')),
                ('dedup_key', models.CharField(db_index=True, max_length=120, verbose_name='聚合键')),
                ('event_count', models.IntegerField(default=1, verbose_name='事件数')),
                ('is_storm', models.BooleanField(default=False, verbose_name='事件风暴')),
                ('is_flapping', models.BooleanField(default=False, verbose_name='抖动')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='发生时刻')),
                ('detected_at', models.DateTimeField(blank=True, null=True, verbose_name='发现时刻')),
                ('plan_ready_at', models.DateTimeField(blank=True, null=True, verbose_name='方案就位时刻')),
                ('acked_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时刻')),
                ('acked_by', models.CharField(blank=True, default='', max_length=50, verbose_name='确认人')),
                ('executing_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时刻')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时刻')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时刻')),
                ('rca_result', models.JSONField(default=dict, verbose_name='根因诊断')),
                ('impact', models.JSONField(default=dict, verbose_name='影响评估')),
                ('plans', models.JSONField(default=list, verbose_name='处置方案')),
                ('health_snapshot', models.FloatField(default=0.0, verbose_name='生成时健康分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='monitor.databaseconfig', verbose_name='数据库')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='monitor.problem', verbose_name='关联问题')),
            ],
            options={
                'verbose_name': '事故',
                'verbose_name_plural': '事故列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uid', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='事件UID')),
                ('db_type', models.CharField(max_length=20, verbose_name='数据库类型')),
                ('source', models.CharField(choices=[('sentinel', '哨兵'), ('collector', '采集器'), ('baseline', '基线'), ('ml', '机器学习'), ('inspection', '巡检')], max_length=20, verbose_name='来源')),
                ('signal', models.CharField(db_index=True, max_length=40, verbose_name='信号')),
                ('metric_key', models.CharField(blank=True, default='', max_length=100, verbose_name='指标键')),
                ('value', models.FloatField(default=0.0, verbose_name='值')),
                ('threshold', models.FloatField(default=0.0, verbose_name='阈值')),
                ('severity', models.CharField(choices=[('critical', '严重'), ('error', '错误'), ('warning', '警告'), ('info', '信息')], db_index=True, max_length=20, verbose_name='严重度')),
                ('dedup_key', models.CharField(db_index=True, max_length=120, verbose_name='去重键')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='发生时刻')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时刻')),
                ('detail', models.JSONField(default=dict, verbose_name='证据')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='monitor.databaseconfig', verbose_name='数据库')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='monitor.incident', verbose_name='归属事故')),
            ],
            options={
                'verbose_name': '事件',
                'verbose_name_plural': '事件列表',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['config', 'signal', 'occurred_at'], name='monitor_eve_config__976bf6_idx'), models.Index(fields=['dedup_key', 'occurred_at'], name='monitor_eve_dedup_k_e639e7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'priority'], name='monitor_inc_status_95275c_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['config', 'category', 'status'], name='monitor_inc_config__6c0d33_idx'),
        ),
    ]
