# Generated by Django 6.0.5 on 2026-07-13 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_problem_incident_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnCallSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班次名')),
                ('user', models.CharField(max_length=50, verbose_name='值班人')),
                ('contact_dingtalk', models.CharField(blank=True, default='', max_length=120, verbose_name='钉钉')),
                ('contact_wecom', models.CharField(blank=True, default='', max_length=120, verbose_name='企微')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=120, verbose_name='电话')),
                ('weekday_mask', models.IntegerField(default=127, help_text='bit0=周一', verbose_name='值班星期位掩码')),
                ('start_hour', models.IntegerField(default=0, verbose_name='值班开始小时')),
                ('end_hour', models.IntegerField(default=24, verbose_name='值班结束小时')),
                ('escalate_to', models.CharField(blank=True, default='', max_length=50, verbose_name='升级联系人')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '值班表',
                'verbose_name_plural': '值班表列表',
            },
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playbook_id', models.CharField(db_index=True, max_length=48, unique=True, verbose_name='剧本ID')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('category', models.CharField(choices=[('availability', '可用性'), ('lock', '锁'), ('connection', '连接'), ('capacity', '容量'), ('replication', '复制'), ('performance', '性能'), ('config', '配置'), ('other', '其他')], db_index=True, max_length=20, verbose_name='类别')),
                ('signal', models.CharField(blank=True, db_index=True, default='', max_length=40, verbose_name='适用信号')),
                ('applicable_db_types', models.JSONField(default=list, verbose_name='适用数据库类型')),
                ('risk_level', models.CharField(choices=[('low', '低'), ('mid', '中'), ('high', '高')], max_length=10, verbose_name='风险级')),
                ('precheck', models.JSONField(default=list, verbose_name='前置检查步骤')),
                ('steps', models.JSONField(default=list, verbose_name='执行步骤')),
                ('verify', models.JSONField(default=dict, verbose_name='验证判据')),
                ('rollback', models.JSONField(default=list, verbose_name='回滚步骤')),
                ('params_schema', models.JSONField(default=dict, verbose_name='参数定义')),
                ('est_minutes', models.IntegerField(default=5, verbose_name='预计耗时(分)')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('auto_execute', models.BooleanField(default=False, verbose_name='允许自动执行')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '处置剧本',
                'verbose_name_plural': '处置剧本列表',
            },
        ),
        migrations.CreateModel(
            name='PlaybookRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=48, unique=True, verbose_name='执行ID')),
                ('params', models.JSONField(default=dict, verbose_name='实际参数')),
                ('status', models.CharField(choices=[('pending_approval', '待审批'), ('prechecking', '前置检查'), ('executing', '执行中'), ('verifying', '验证中'), ('succeeded', '成功'), ('failed', '失败'), ('rolled_back', '已回滚'), ('timeout', '验证超时')], db_index=True, default='pending_approval', max_length=20, verbose_name='状态')),
                ('trigger_mode', models.CharField(choices=[('auto', '自动'), ('one_click', '一键'), ('approved', '审批通过')], max_length=12, verbose_name='触发方式')),
                ('approved_by', models.CharField(blank=True, default='', max_length=50, verbose_name='审批人')),
                ('step_results', models.JSONField(default=list, verbose_name='步骤结果')),
                ('verify_result', models.JSONField(default=dict, verbose_name='验证结果')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbook_runs', to='monitor.incident', verbose_name='事故')),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='monitor.playbook', verbose_name='剧本')),
            ],
            options={
                'verbose_name': '剧本执行',
                'verbose_name_plural': '剧本执行列表',
                'ordering': ['-created_at'],
            },
        ),
    ]
