# Generated by Django 6.0.5 on 2026-07-14 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0015_oncallschedule_playbook_playbookrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconfig',
            name='cpu_cores',
            field=models.IntegerField(blank=True, null=True, verbose_name='CPU核数'),
        ),
        migrations.CreateModel(
            name='SqlPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql_digest', models.CharField(db_index=True, max_length=32, verbose_name='SQL指纹')),
                ('plan_hash', models.CharField(max_length=32, verbose_name='计划指纹')),
                ('plan_json', models.JSONField(default=dict, verbose_name='计划(JSON)')),
                ('plan_text', models.TextField(blank=True, default='', verbose_name='计划(文本)')),
                ('cost_total', models.FloatField(blank=True, null=True, verbose_name='总代价')),
                ('source', models.CharField(choices=[('auto', '自动'), ('manual', '手动'), ('incident', '事故')], default='auto', max_length=12, verbose_name='来源')),
                ('captured_at', models.DateTimeField(auto_now_add=True, verbose_name='采集时间')),
                ('is_current', models.BooleanField(default=True, verbose_name='当前计划')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sql_plans', to='monitor.databaseconfig', verbose_name='数据库')),
            ],
            options={
                'verbose_name': 'SQL执行计划',
                'verbose_name_plural': 'SQL执行计划列表',
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['config', 'sql_digest', 'is_current'], name='monitor_sql_config__e893db_idx')],
            },
        ),
    ]
