# Generated by Django 6.0.5 on 2026-07-27 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0016_databaseconfig_cpu_cores_sqlplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene', models.CharField(choices=[('diagnosis', '事故诊断'), ('plan_draft', '方案草拟'), ('distill', '案例蒸馏'), ('agent', '主动排查'), ('embed', '向量化'), ('test', '连通测试')], db_index=True, max_length=12, verbose_name='场景')),
                ('incident_id', models.CharField(blank=True, db_index=True, default='', max_length=48, verbose_name='关联事故')),
                ('provider', models.CharField(blank=True, default='', max_length=20, verbose_name='Provider')),
                ('model', models.CharField(blank=True, default='', max_length=64, verbose_name='模型')),
                ('status', models.CharField(choices=[('ok', '成功'), ('timeout', '超时'), ('unavailable', '不可用'), ('bad_json', '输出不合法'), ('error', '其他错误')], db_index=True, max_length=12, verbose_name='状态')),
                ('latency_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='提示词token')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='补全token')),
                ('prompt_chars', models.IntegerField(default=0, verbose_name='提示词字符数')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('response_digest', models.CharField(blank=True, default='', max_length=32, verbose_name='响应摘要指纹')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'LLM调用日志',
                'verbose_name_plural': 'LLM调用日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleStat',
            fields=[
                ('rule_id', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='规则ID')),
                ('hit_count', models.IntegerField(default=0, verbose_name='命中次数')),
                ('correct_count', models.IntegerField(default=0, verbose_name='确认准确次数')),
                ('wrong_count', models.IntegerField(default=0, verbose_name='确认不准次数')),
                ('accuracy', models.FloatField(default=0.0, verbose_name='准确率')),
                ('calibrated_base', models.FloatField(default=0.6, verbose_name='校准后基础置信度')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '规则统计',
                'verbose_name_plural': '规则统计列表',
            },
        ),
        migrations.AddField(
            model_name='alertcase',
            name='embedding_indexed',
            field=models.BooleanField(default=False, help_text='True=已写入 ES db_cases 向量索引', verbose_name='向量已索引'),
        ),
        migrations.AddField(
            model_name='alertcase',
            name='source',
            field=models.CharField(db_index=True, default='manual', help_text='manual=人工录入 distilled=事故自动蒸馏 seed=初始化种子', max_length=12, verbose_name='案例来源'),
        ),
        migrations.AddField(
            model_name='alertcase',
            name='source_incident',
            field=models.CharField(blank=True, db_index=True, default='', max_length=48, verbose_name='来源事故ID'),
        ),
        migrations.AddField(
            model_name='databaseconfig',
            name='autonomy_level',
            field=models.IntegerField(blank=True, help_text='留空表示跟随全局默认; 0-3 逐级放权', null=True, verbose_name='自治等级'),
        ),
        migrations.CreateModel(
            name='AgentTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=48, unique=True, verbose_name='轨迹ID')),
                ('status', models.CharField(choices=[('running', '运行中'), ('done', '完成'), ('failed', '失败'), ('budget_exceeded', '预算耗尽')], default='running', max_length=16, verbose_name='状态')),
                ('steps', models.JSONField(default=list, help_text='[{step,thought,action,params,observation,elapsed_ms}]', verbose_name='步骤序列')),
                ('conclusion', models.JSONField(default=dict, verbose_name='最终结论')),
                ('triggered_by', models.CharField(default='system', max_length=50, verbose_name='触发人')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_traces', to='monitor.incident', verbose_name='事故')),
            ],
            options={
                'verbose_name': 'Agent排查轨迹',
                'verbose_name_plural': 'Agent排查轨迹列表',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CausalEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause_metric', models.CharField(max_length=64, verbose_name='因指标')),
                ('effect_metric', models.CharField(max_length=64, verbose_name='果指标')),
                ('lag_minutes', models.IntegerField(default=5, verbose_name='滞后(分)')),
                ('strength', models.FloatField(default=0.0, verbose_name='强度(相关系数)')),
                ('sample_days', models.IntegerField(default=7, verbose_name='样本天数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causal_edges', to='monitor.databaseconfig', verbose_name='数据库')),
            ],
            options={
                'verbose_name': '因果边',
                'verbose_name_plural': '因果边列表',
                'constraints': [models.UniqueConstraint(fields=('config', 'cause_metric', 'effect_metric'), name='uniq_causal_cfg_cause_effect')],
            },
        ),
        migrations.CreateModel(
            name='ChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('config_drift', '参数漂移'), ('ddl', 'DDL变更'), ('manual', '人工登记'), ('audit', '审计提取')], db_index=True, max_length=16, verbose_name='来源')),
                ('change_type', models.CharField(blank=True, default='', max_length=40, verbose_name='变更类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('detail', models.JSONField(default=dict, help_text='如 {param, old, new} 或 {ddl_text}', verbose_name='详情')),
                ('operator', models.CharField(blank=True, default='', max_length=50, verbose_name='操作人')),
                ('dedup_key', models.CharField(max_length=64, unique=True, verbose_name='去重键')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='发生时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='monitor.databaseconfig', verbose_name='数据库')),
            ],
            options={
                'verbose_name': '变更事件',
                'verbose_name_plural': '变更事件流',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['config', 'occurred_at'], name='monitor_cha_config__5db899_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(help_text='conservative/standard/aggressive/llm_advisory', max_length=20, verbose_name='方案场景')),
                ('verdict', models.CharField(choices=[('adopted', '采纳且有效'), ('adopted_failed', '采纳但无效'), ('rejected', '未采纳')], max_length=16, verbose_name='结论')),
                ('comment', models.TextField(blank=True, default='', verbose_name='备注')),
                ('user', models.CharField(max_length=50, verbose_name='反馈人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_feedbacks', to='monitor.incident', verbose_name='事故')),
            ],
            options={
                'verbose_name': '方案反馈',
                'verbose_name_plural': '方案反馈列表',
                'constraints': [models.UniqueConstraint(fields=('incident', 'scenario', 'user'), name='uniq_planfb_inc_scen_user')],
            },
        ),
        migrations.CreateModel(
            name='RcaFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(db_index=True, max_length=24, verbose_name='规则/假设ID')),
                ('source', models.CharField(default='rules', help_text='rules/llm/both', max_length=12, verbose_name='根因来源')),
                ('verdict', models.CharField(choices=[('correct', '准确'), ('wrong', '不准'), ('partial', '部分准确')], max_length=12, verbose_name='结论')),
                ('actual_cause', models.TextField(blank=True, default='', verbose_name='实际根因(否定时填)')),
                ('user', models.CharField(max_length=50, verbose_name='反馈人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rca_feedbacks', to='monitor.incident', verbose_name='事故')),
            ],
            options={
                'verbose_name': '根因反馈',
                'verbose_name_plural': '根因反馈列表',
                'constraints': [models.UniqueConstraint(fields=('incident', 'rule_id', 'user'), name='uniq_rcafb_inc_rule_user')],
            },
        ),
    ]
