# Generated by Django 5.2.17 on 2026-08-09 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0019_userprofiledatabase_config_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="config",
            field=models.ForeignKey(
                blank=True,
                help_text="平台级操作（登录/用户/角色）无关联实例，可为空",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="monitor.databaseconfig",
                verbose_name="数据库",
            ),
        ),
    ]
