# Generated by Django 6.0.5 on 2026-08-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0021_sqlplan_unique_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('collector', '指标采集器'), ('sentinel', '哨兵/ASH采样'), ('pipeline', '事件流水线消费者'), ('notifier', '通知发送器')], max_length=32, verbose_name='组件')),
                ('instance', models.CharField(help_text='hostname:pid，区分多副本部署', max_length=128, verbose_name='实例标识')),
                ('last_beat_at', models.DateTimeField(db_index=True, verbose_name='最后心跳时间')),
                ('status', models.CharField(choices=[('up', '正常'), ('down', '失联')], default='up', max_length=8, verbose_name='状态')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='如采集实例数、队列积压等，仅供展示', verbose_name='附加信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='首次上报')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '组件心跳',
                'verbose_name_plural': '组件心跳列表',
                'indexes': [models.Index(fields=['status', 'last_beat_at'], name='monitor_com_status_cb6cc3_idx')],
                'unique_together': {('component', 'instance')},
            },
        ),
    ]
