# Generated by Django 6.0.5 on 2026-08-16 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0022_componentheartbeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybookTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='剧本编码')),
                ('name', models.CharField(max_length=128, verbose_name='剧本名称')),
                ('db_types', models.JSONField(default=list, verbose_name='适用数据库类型')),
                ('risk_level', models.CharField(choices=[('low', '低风险 (可自愈)'), ('medium', '中风险 (建议确认)'), ('high', '高风险 (需双人审批)'), ('critical', '极高风险 (强制阻断)')], default='medium', max_length=16, verbose_name='风险等级')),
                ('min_autonomy_level', models.IntegerField(default=1, verbose_name='最低自治等级')),
                ('steps_payload', models.JSONField(default=list, verbose_name='执行步骤序列')),
                ('rollback_payload', models.JSONField(blank=True, default=list, verbose_name='逆向回滚步骤')),
                ('description', models.TextField(blank=True, verbose_name='剧本描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '自愈剧本模板',
                'verbose_name_plural': '自愈剧本模板列表',
            },
        ),
        migrations.CreateModel(
            name='DatabaseMetricProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_type', models.CharField(choices=[('oltp', '高频联机交易 OLTP'), ('olap', '分析统计报表 OLAP'), ('mixed', '混合负载 MIXED'), ('batch', '夜间批处理 BATCH')], default='mixed', max_length=32, verbose_name='负载分类')),
                ('cpu_cores', models.IntegerField(blank=True, null=True, verbose_name='CPU核数')),
                ('memory_gb', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='内存(GB)')),
                ('data_disk_gb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='磁盘空间(GB)')),
                ('max_qps', models.IntegerField(default=0, verbose_name='峰值QPS')),
                ('peak_hours_json', models.JSONField(blank=True, default=list, verbose_name='高峰时间段(0-23)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('config', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='v2_profile', to='monitor.databaseconfig', verbose_name='数据库配置')),
            ],
            options={
                'verbose_name': '实例画像基线',
                'verbose_name_plural': '实例画像基线列表',
            },
        ),
        migrations.CreateModel(
            name='PlaybookRunRecord',
            fields=[
                ('run_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='执行ID')),
                ('operator', models.CharField(max_length=64, verbose_name='操作人')),
                ('status', models.CharField(choices=[('dryrun_passed', '预演通过'), ('dryrun_rejected', '预演驳回'), ('approved', '已审批待执行'), ('running', '正在执行'), ('success', '执行成功'), ('failed', '执行失败'), ('rolled_back', '已自动回滚')], default='dryrun_passed', max_length=32, verbose_name='执行状态')),
                ('dryrun_result', models.JSONField(blank=True, default=dict, verbose_name='预演评估结果')),
                ('execution_result', models.JSONField(blank=True, default=dict, verbose_name='执行产出结果')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbook_run_records', to='monitor.databaseconfig', verbose_name='目标数据库')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playbook_run_records', to='monitor.incident', verbose_name='关联事故')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_records', to='monitor.playbooktemplate', verbose_name='关联剧本')),
            ],
            options={
                'verbose_name': '自愈执行记录',
                'verbose_name_plural': '自愈执行记录列表',
            },
        ),
        migrations.CreateModel(
            name='IncidentCauseChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_seq', models.IntegerField(verbose_name='步骤序号')),
                ('node_type', models.CharField(choices=[('CHANGE', '变更事件/DDL'), ('SQL', 'SQL执行/全表扫'), ('RESOURCE', '资源耗尽/水位'), ('LOCK', '锁等待/阻塞源'), ('CLUSTER', '集群节点/复制延迟')], max_length=32, verbose_name='节点类型')),
                ('node_name', models.CharField(max_length=128, verbose_name='节点名称')),
                ('description', models.TextField(verbose_name='节点推理描述')),
                ('evidence_refs', models.JSONField(blank=True, default=list, verbose_name='关联证据编号列表')),
                ('confidence', models.DecimalField(decimal_places=3, default=1.0, max_digits=4, verbose_name='置信度')),
                ('metric_snapshot', models.JSONField(blank=True, default=dict, verbose_name='触发时指标快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cause_chains', to='monitor.incident', verbose_name='关联事故')),
            ],
            options={
                'verbose_name': '故障因果链节点',
                'verbose_name_plural': '故障因果链节点列表',
                'ordering': ['incident', 'step_seq'],
                'unique_together': {('incident', 'step_seq')},
            },
        ),
    ]
