# Generated by Django 6.0.5 on 2026-08-16 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0023_playbooktemplate_databasemetricprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如 MiniMax-主力账号01', max_length=64, verbose_name='配置名称')),
                ('provider_type', models.CharField(choices=[('minimax', 'MiniMax 名之梦'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek 深度求索'), ('openai', 'OpenAI 官方'), ('qwen', '阿里通义千问'), ('moonshot', '月之暗面 Kimi'), ('ollama', '本地私有 Ollama'), ('custom', '自定义兼容端点')], default='custom', max_length=32, verbose_name='供应商类型')),
                ('base_url', models.CharField(max_length=255, verbose_name='API 接入端点 Base URL')),
                ('api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='加密存储的 API Key')),
                ('model_name', models.CharField(help_text='如 MiniMax-Text-01 / gemini-1.5-pro', max_length=64, verbose_name='模型 ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('priority', models.IntegerField(default=10, help_text='数字越小优先级越高 (1-100)', verbose_name='优先级')),
                ('weight', models.IntegerField(default=1, verbose_name='负载权重')),
                ('is_healthy', models.BooleanField(default=True, verbose_name='是否健康')),
                ('cooldown_until', models.DateTimeField(blank=True, null=True, verbose_name='429 冷却截止时间')),
                ('consecutive_fails', models.IntegerField(default=0, verbose_name='连续失败计数')),
                ('last_error_message', models.TextField(blank=True, default='', verbose_name='最近一次错误')),
                ('last_latency_ms', models.IntegerField(default=0, verbose_name='最近一次响应耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'LLM 提供商凭据',
                'verbose_name_plural': 'LLM 提供商凭据列表',
                'db_table': 'llm_provider_credential',
                'ordering': ['priority', '-weight', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LLMSceneRoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_code', models.CharField(choices=[('global_default', '全局默认兜底'), ('copilot_chat', 'Copilot 专家日常对话'), ('rca_deep_reasoning', 'RCA 3.0 根因深度推理'), ('sql_explain_opt', 'SQL 执行计划与索引优化'), ('incident_warroom', '排障作战室自愈决策')], max_length=64, unique=True, verbose_name='场景编码')),
                ('scene_name', models.CharField(max_length=64, verbose_name='场景名称')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='场景说明')),
                ('temperature', models.FloatField(default=0.1, verbose_name='发散度 Temperature')),
                ('timeout_sec', models.IntegerField(default=20, verbose_name='超时时间(秒)')),
                ('max_tokens', models.IntegerField(default=2048, verbose_name='最大 Tokens')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('fallback_credentials', models.ManyToManyField(blank=True, related_name='fallback_routes', to='monitor.llmprovidercredential', verbose_name='备选模型凭据链')),
                ('primary_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_routes', to='monitor.llmprovidercredential', verbose_name='主选模型凭据')),
            ],
            options={
                'verbose_name': 'LLM 场景路由规则',
                'verbose_name_plural': 'LLM 场景路由规则列表',
                'db_table': 'llm_scene_routing_rule',
            },
        ),
    ]
