# Generated by Django 6.0.5 on 2026-08-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0024_llmprovidercredential_llmsceneroutingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmprovidercredential',
            name='proxy_url',
            field=models.CharField(blank=True, default='', help_text='如 http://127.0.0.1:7890 / socks5://127.0.0.1:1080', max_length=255, verbose_name='本地代理 URL'),
        ),
    ]
