# Generated by Django 6.0.5 on 2026-08-16 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0025_llmprovidercredential_proxy_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Skill 唯一编码')),
                ('name', models.CharField(max_length=128, verbose_name='Skill 名称')),
                ('source', models.CharField(choices=[('builtin', '系统内置专家 Skill'), ('self_learned', '智能体自总结沉淀 Skill'), ('mcp_imported', 'MCP 协议纳管 Skill'), ('community', '社区/外部导入 Skill')], default='builtin', max_length=32, verbose_name='Skill 来源')),
                ('db_types', models.JSONField(default=list, help_text="如 ['oracle', 'mysql']", verbose_name='适用数据库类型列表')),
                ('description', models.TextField(verbose_name='Skill 职能说明')),
                ('trigger_patterns', models.JSONField(default=list, verbose_name='触发关键词/意图规则')),
                ('system_instruction', models.TextField(blank=True, default='', verbose_name='Skill 专属推理指导 Prompt')),
                ('diagnostic_sqls', models.JSONField(blank=True, default=list, verbose_name='标准诊断 SQL 库')),
                ('recommended_playbooks', models.JSONField(blank=True, default=list, verbose_name='推荐自愈剧本编码列表')),
                ('mcp_server_name', models.CharField(blank=True, default='', max_length=128, verbose_name='MCP Server 标识')),
                ('mcp_tool_name', models.CharField(blank=True, default='', max_length=128, verbose_name='MCP Tool 名称')),
                ('mcp_schema', models.JSONField(blank=True, null=True, verbose_name='MCP Tool Schema 定义')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('usage_count', models.IntegerField(default=0, verbose_name='调用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Copilot 专家 Skill',
                'verbose_name_plural': 'Copilot 专家 Skill 库',
                'db_table': 'copilot_skill',
                'ordering': ['source', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CopilotMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('episodic', '情景记忆 (故障处置/自愈工单/事故总结)'), ('semantic', '语义记忆 (架构特征/业务重要性/拓扑知识)'), ('preference', '偏好记忆 (DBA 运维习惯/禁忌/首选方案)')], default='episodic', max_length=32, verbose_name='记忆类型')),
                ('locus_key', models.CharField(db_index=True, help_text='如 oracle:tablespace:full / mysql:deadlock', max_length=128, verbose_name='记忆宫殿坐标 Key')),
                ('title', models.CharField(max_length=255, verbose_name='记忆摘要/标题')),
                ('content', models.TextField(verbose_name='记忆详细内容/排障推导/处置证据')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='记忆标签列表')),
                ('importance', models.IntegerField(default=5, help_text='越高在检索时越优先唤醒', verbose_name='重要度 (1-10)')),
                ('access_count', models.IntegerField(default=0, verbose_name='被回忆/引用次数')),
                ('last_recalled_at', models.DateTimeField(blank=True, null=True, verbose_name='最后一次回忆时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='沉淀时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('audit_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='monitor.auditlog', verbose_name='关联工单')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_memories', to='monitor.databaseconfig', verbose_name='关联数据库')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memories', to='monitor.incident', verbose_name='关联事故')),
            ],
            options={
                'verbose_name': 'Copilot 长期记忆',
                'verbose_name_plural': 'Copilot 长期记忆库',
                'db_table': 'copilot_memory',
                'ordering': ['-importance', '-updated_at'],
            },
        ),
    ]
