# Generated by Django 6.0.5 on 2026-08-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0026_copilotskill_copilotmemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconfig',
            name='collect_interval_sec',
            field=models.IntegerField(default=60, help_text='默认60秒 (支持10s-3600s)', verbose_name='指标采集周期(秒)'),
        ),
        migrations.AddField(
            model_name='databaseconfig',
            name='template_name',
            field=models.CharField(blank=True, default='', help_text='如 standard_oracle / high_frequency_mysql', max_length=64, verbose_name='配置模板名称'),
        ),
    ]
