# Generated by Django 6.0.5 on 2026-08-16 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0027_databaseconfig_collect_interval_sec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBCollectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：Oracle 核心高频模板', max_length=100, verbose_name='模板名称')),
                ('code', models.CharField(help_text='如 oracle_core_high_freq', max_length=64, unique=True, verbose_name='模板编码')),
                ('db_type', models.CharField(choices=[('oracle', 'Oracle'), ('mysql', 'MySQL'), ('redis', 'Redis'), ('pgsql', 'PostgreSQL'), ('mongo', 'MongoDB'), ('dm', '达梦数据库'), ('gbase', 'Gbase 8a'), ('tdsql', 'TDSQL')], max_length=20, verbose_name='数据库类型')),
                ('default_port', models.IntegerField(default=3306, verbose_name='推荐端口')),
                ('collect_interval_sec', models.IntegerField(default=60, help_text='10-3600秒', verbose_name='推荐采集周期(秒)')),
                ('default_service_name', models.CharField(blank=True, default='', max_length=100, verbose_name='默认服务名/SID')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否为系统内置模板')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否为该类型默认模板')),
                ('description', models.TextField(blank=True, default='', verbose_name='模板描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('associated_alert_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_collect_templates', to='monitor.alerttemplate', verbose_name='推荐关联告警模板组')),
            ],
            options={
                'verbose_name': '采集配置模板',
                'verbose_name_plural': '采集配置模板列表',
                'ordering': ['db_type', '-is_default', 'name'],
            },
        ),
    ]
