# Generated by Django 5.2.17 on 2026-08-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0028_dbcollecttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=32, verbose_name='后台角色')),
                ('shard_key', models.CharField(default='global', max_length=128, verbose_name='分片键')),
                ('owner_id', models.CharField(blank=True, default='', max_length=160, verbose_name='持有者')),
                ('fencing_token', models.BigIntegerField(default=0, verbose_name='隔离令牌')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='租约到期时间')),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='续租时间')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='租约元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '进程租约',
                'verbose_name_plural': '进程租约列表',
                'db_table': 'process_lease',
                'indexes': [models.Index(fields=['role', 'expires_at'], name='process_lea_role_8156eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('role', 'shard_key'), name='uniq_process_lease_role_shard')],
            },
        ),
    ]
