"""
智能巡检规则库 v1.0 (Phase 5)

定义 60+ 巡检项,涵盖:
- 30 项通用巡检 (6 库通用)
- 30 项 Oracle 专项
- 20+ 项 MySQL/PG/DM/GBase/TDSQL 专项

设计文档参考: PHASE5_DEVELOPMENT_DESIGN.md 第三部分 P1-1~P1-4
"""
from typing import List, Dict, Any


# ==========================================
# 通用巡检项 (30 项, 6 库通用)
# ==========================================
COMMON_ITEMS: List[Dict[str, Any]] = [
    {
        'item_id': 'INS-COM-INVALID-OBJ',
        'title': '无效对象检查',
        'category': 'object',
        'level': 'daily',
        'severity': 'warn',
        'applicable_db_types': ['oracle', 'dm', 'gbase'],
        'description': '检测数据库中的无效对象(视图/包/存储过程)',
        'detect_method': 'detect_invalid_objects',
        'threshold': {'warn': 1, 'error': 10, 'critical': 50},
        'recommendation': '使用 @?/rdbms/admin/utlrp.sql 重新编译所有无效对象',
        'auto_fixable': True,
        'auto_fix_method': 'compile_invalid_objects',
        'references': ['Oracle MOS 1454876.1'],
    },
    {
        'item_id': 'INS-COM-RECYCLEBIN',
        'title': '回收站清理检查',
        'category': 'object',
        'level': 'weekly',
        'severity': 'warn',
        'applicable_db_types': ['oracle', 'dm'],
        'description': '回收站中残留对象数量过多,占用空间',
        'detect_method': 'detect_recyclebin',
        'threshold': {'warn': 50, 'error': 200, 'critical': 1000},
        'recommendation': '使用 PURGE RECYCLEBIN 清理回收站',
        'auto_fixable': True,
        'auto_fix_method': 'purge_recyclebin',
        'references': ['Oracle Recyclebin 管理'],
    },
    {
        'item_id': 'INS-COM-USER-LOCKED',
        'title': '账号锁定检查',
        'category': 'security',
        'level': 'daily',
        'severity': 'warn',
        'applicable_db_types': ['oracle', 'mysql', 'pgsql', 'dm', 'gbase', 'tdsql'],
        'description': '是否存在被锁定的账号',
        'detect_method': 'detect_locked_users',
        'threshold': {'warn': 1, 'error': 3, 'critical': 10},
        'recommendation': '核查账号是否应解锁;非必要账号可删除',
        'auto_fixable': False,
        'references': [],
    },
    {
        'item_id': 'INS-COM-PWD-EXPIRE',
        'title': '密码即将过期',
        'category': 'security',
        'level': 'daily',
        'severity': 'warn',
        'applicable_db_types': ['oracle', 'mysql', 'pgsql', 'dm', 'gbase', 'tdsql'],
        'description': '7 天内即将过期的账号',
        'detect_method': 'detect_expiring_passwords',
        'threshold': {'warn': 1, 'error': 3, 'critical': 10},
        'recommendation': '提前通知账号负责人修改密码',
        'auto_fixable': False,
        'references': [],
    },
    {
        'item_id': 'INS-COM-CAP-7D',
        'title': '7天容量预测',
        'category': 'capacity',
        'level': 'daily',
        'severity': 'info',
        'applicable_db_types': ['oracle', 'mysql', 'pgsql', 'dm', 'gbase', 'tdsql'],
        'description': '7 天内将达到告警阈值的资源',
        'detect_method': 'detect_7d_capacity',
        'threshold': {'warn': 1, 'error': 3, 'critical': 5},
        'recommendation': '提前扩容或归档',
        'auto_fixable': False,
        'references': [],
    },
    {
        'item_id': 'INS-COM-CAP-30D',
        'title': '30天容量预测',
        'category': 'capacity',
        'level': 'weekly',
        'severity': 'info',
        'applicable_db_types': ['oracle', 'mysql', 'pgsql', 'dm', 'gbase', 'tdsql'],
        'description': '30 天内将达到告警阈值的资源',
        'detect_method': 'detect_30d_capacity',
        'threshold': {'warn': 1, 'error': 3, 'critical': 5},
        'recommendation': '规划扩容',
        'auto_fixable': False,
        'references': [],
    },
    {
        'item_id': 'INS-COM-CONN-PEAK',
        'title': '连接峰值检查',
        'category': 'performance',
        'level': 'daily',
        'severity': 'info',
        'applicable_db_types': ['oracle', 'mysql', 'pgsql', 'dm', 'gbase', 'tdsql'],
        'description': '24h 内连接使用率峰值',
        'detect_method': 'detect_conn_peak',
        'threshold': {'warn': 80, 'error': 90, 'critical': 95},
        'recommendation': '评估连接池配置',
        'auto_fixable': False,
        'references': [],
    },
    {
        'item_id': 'INS-COM-LONG-TXN',
        'title': '长事务检查',
        'category': 'performance',
        'level': 'daily',
        'severity': 'warn',
        'applicable_db_types': ['oracle', 'mysql', 'pgsql', 'dm', 'gbase', 'tdsql'],
        'description': '运行超过 30 分钟的事务',
        'detect_method': 'detect_long_transactions',
        'threshold': {'warn': 1, 'error': 5, 'critical': 10},
        'recommendation': '排查长事务,评估 kill 影响',
        'auto_fixable': True,
        'auto_fix_method': 'kill_long_transactions',
        'references': [],
    },
    {
        'item_id': 'INS-COM-DEADLOCK-24H',
        'title': '24h 死锁次数',
        'category': 'performance',
        'level': 'daily',
        'severity': 'warn',
        'applicable_db_types': ['oracle', 'mysql', 'pgsql', 'dm', 'gbase', 'tdsql'],
        'description': '24 小时内死锁发生次数',
        'detect_method': 'detect_deadlock_count',
        'threshold': {'warn': 1, 'error': 10, 'critical': 50},
        'recommendation': '分析死锁 trace,优化应用层事务顺序',
        'auto_fixable': False,
        'references': [],
    },
    {
        'item_id': 'INS-COM-SLOW-LOG',
        'title': '慢查询日志检查',
        'category': 'performance',
        'level': 'daily',
        'severity': 'info',
        'applicable_db_types': ['oracle', 'mysql', 'pgsql', 'dm', 'gbase', 'tdsql'],
        'description': '慢查询日志大小/开启状态',
        'detect_method': 'detect_slow_query_log',
        'threshold': {'warn': 1, 'error': 3, 'critical': 5},
        'recommendation': '确保慢查询日志已开启',
        'auto_fixable': False,
        'references': [],
    },
    {
        'item_id': 'INS-COM-INDEX-USAGE',
        'title': '索引使用率检查',
        'category': 'index',
        'level': 'weekly',
        'severity': 'info',
        'applicable_db_types': ['oracle', 'mysql', 'pgsql', 'dm', 'gbase', 'tdsql'],
        'description': '过去 30 天从未被使用的索引',
        'detect_method': 'detect_unused_indexes',
        'threshold': {'warn': 5, 'error': 20, 'critical': 50},
        'recommendation': '考虑删除未使用的索引以减少 DML 开销',
        'auto_fixable': True,
        'auto_fix_method': 'drop_unused_indexes',
        'references': [],
    },
    {
        'item_id': 'INS-COM-MISSING-INDEX',
        'title': '缺失索引检查',
        'category': 'index',
        'level': 'weekly',
        'severity': 'warn',
        'applicable_db_types': ['oracle', 'mysql', 'pgsql', 'dm'],
        'description': '基于高 cost 扫描推荐缺失索引',
        'detect_method': 'detect_missing_indexes',
        'threshold': {'warn': 1, 'error': 5, 'critical': 10},
        'recommendation': '运行 index_advisor 推荐索引',
        'auto_fixable': False,
        'references': [],
    },
    {
        'item_id': 'INS-COM-FK-NO-INDEX',
        'title': '外键无索引',
        'category': 'index',
        'level': 'weekly',
        'severity': 'warn',
        'applicable_db_types': ['oracle', 'mysql', 'pgsql', 'dm'],
        'description': '外键列上无索引,会导致锁升级',
        'detect_method': 'detect_fk_no_index',
        'threshold': {'warn': 1, 'error': 5, 'critical': 10},
        'recommendation': '为外键列创建索引',
        'auto_fixable': True,
        'auto_fix_method': 'create_fk_indexes',
        'references': ['Oracle MOS 223303.1'],
    },
    {
        'item_id': 'INS-COM-PART-NEEDED',
        'title': '大表未分区',
        'category': 'object',
        'level': 'monthly',
        'severity': 'info',
        'applicable_db_types': ['oracle', 'mysql', 'pgsql', 'dm', 'gbase'],
        'description': '超过 100GB 的表未分区',
        'detect_method': 'detect_large_table_not_partitioned',
        'threshold': {'warn': 1, 'error': 3, 'critical': 5},
        'recommendation': '考虑按时间/范围分区',
        'auto_fixable': False,
        'references': [],
    },
    {
        'item_id': 'INS-COM-STAT-STALE',
        'title': '统计信息过期',
        'category': 'statistics',
        'level': 'weekly',
        'severity': 'warn',
        'applicable_db_types': ['oracle', 'mysql', 'pgsql', 'dm', 'gbase', 'tdsql'],
        'description': '超过 7 天未收集统计信息的表',
        'detect_method': 'detect_stale_stats',
        'threshold': {'warn': 10, 'error': 50, 'critical': 200},
        'recommendation': '收集统计信息',
        'auto_fixable': True,
        'auto_fix_method': 'gather_stats',
        'references': [],
    },
    {
        'item_id': 'INS-COM-SPARSE-INDEX',
        'title': '稀疏索引',
        'category': 'index',
        'level': 'monthly',
        'severity': 'info',
        'applicable_db_types': ['oracle', 'mysql', 'pgsql', 'dm'],
        'description': 'distinct 比例 < 5% 的索引(选择性差)',
        'detect_method': 'detect_sparse_index',
        'threshold': {'warn': 5, 'error': 20, 'critical': 50},
        'recommendation': '考虑删除或重建为复合索引',
        'auto_fixable': False,
        'references': [],
    },
    {
        'item_id': 'INS-COM-BLEVEL-HIGH',
        'title': '高 BLEVEL 索引',
        'category': 'index',
        'level': 'monthly',
        'severity': 'warn',
        'applicable_db_types': ['oracle', 'mysql', 'pgsql', 'dm'],
        'description': 'Blevel > 4 的索引,查询效率低',
        'detect_method': 'detect_high_blevel_index',
        'threshold': {'warn': 5, 'error': 20, 'critical': 50},
        'recommendation': '考虑 REBUILD 索引',
        'auto_fixable': True,
        'auto_fix_method': 'rebuild_high_blevel',
        'references': [],
    },
    {
        'item_id': 'INS-COM-SEQ-MAX',
        'title': '序列接近 MAX',
        'category': 'sequence',
        'level': 'daily',
        'severity': 'warn',
        'applicable_db_types': ['oracle', 'dm', 'pgsql'],
        'description': '序列使用率超过 80%',
        'detect_method': 'detect_seq_near_max',
        'threshold': {'warn': 1, 'error': 3, 'critical': 5},
        'recommendation': '扩 MAXVALUE 或新建序列',
        'auto_fixable': True,
        'auto_fix_method': 'extend_sequence',
        'references': [],
    },
    {
        'item_id': 'INS-COM-SEQ-NO-CACHE',
        'title': '序列无 CACHE',
        'category': 'sequence',
        'level': 'monthly',
        'severity': 'info',
        'applicable_db_types': ['oracle', 'dm'],
        'description': '频繁访问但未设置 CACHE 的序列',
        'detect_method': 'detect_seq_no_cache',
        'threshold': {'warn': 1, 'error': 5, 'critical': 20},
        'recommendation': '设置 CACHE 提升性能',
        'auto_fixable': False,
        'references': [],
    },
    {
        'item_id': 'INS-COM-PARAM-DEV',
        'title': '参数偏离最佳实践',
        'category': 'config',
        'level': 'monthly',
        'severity': 'info',
        'applicable_db_types': ['oracle', 'mysql', 'pgsql', 'dm', 'gbase'],
        'description': '关键参数与推荐值偏差',
        'detect_method': 'detect_param_deviation',
        'threshold': {'warn': 5, 'error': 10, 'critical': 20},
        'recommendation': '运行 config_advisor 评估',
        'auto_fixable': False,
        'references': [],
    },
    {
        'item_id': 'INS-COM-BACKUP',
        'title': '备份状态',
        'category': 'operations',
        'level': 'daily',
        'severity': 'error',
        'applicable_db_types': ['oracle', 'mysql', 'pgsql', 'dm', 'gbase', 'tdsql'],
        'description': '24h 内是否有成功备份',
        'detect_method': 'detect_backup_status',
        'threshold': {'warn': 1, 'error': 2, 'critical': 3},
        'recommendation': '检查备份策略,确认 RPO',
        'auto_fixable': False,
        'references': [],
    },
    {
        'item_id': 'INS-COM-ARCH-GAP',
        'title': '归档间隙',
        'category': 'log',
        'level': 'daily',
        'severity': 'error',
        'applicable_db_types': ['oracle', 'dm'],
        'description': '归档日志存在 gap',
        'detect_method': 'detect_archive_gap',
        'threshold': {'warn': 1, 'error': 5, 'critical': 20},
        'recommendation': '检查归档目录空间和网络',
        'auto_fixable': False,
        'references': [],
    },
    {
        'item_id': 'INS-COM-LOG-SWITCH',
        'title': '日志切换频率',
        'category': 'log',
        'level': 'daily',
        'severity': 'warn',
        'applicable_db_types': ['oracle', 'dm'],
        'description': 'redo log 每小时切换次数',
        'detect_method': 'detect_log_switches',
        'threshold': {'warn': 10, 'error': 20, 'critical': 50},
        'recommendation': '增大 redo log 文件',
        'auto_fixable': False,
        'references': [],
    },
    {
        'item_id': 'INS-COM-LOCK-WAIT',
        'title': '当前锁等待',
        'category': 'performance',
        'level': 'daily',
        'severity': 'warn',
        'applicable_db_types': ['oracle', 'mysql', 'pgsql', 'dm', 'gbase', 'tdsql'],
        'description': '当前存在的锁等待',
        'detect_method': 'detect_lock_waits',
        'threshold': {'warn': 5, 'error': 20, 'critical': 50},
        'recommendation': '分析锁等待链',
        'auto_fixable': False,
        'references': [],
    },
    {
        'item_id': 'INS-COM-BLOCK-SESSION',
        'title': '被阻塞会话',
        'category': 'performance',
        'level': 'daily',
        'severity': 'warn',
        'applicable_db_types': ['oracle', 'mysql', 'pgsql', 'dm', 'gbase', 'tdsql'],
        'description': '被阻塞超过 5 分钟的会话',
        'detect_method': 'detect_blocked_sessions',
        'threshold': {'warn': 1, 'error': 5, 'critical': 20},
        'recommendation': 'kill 阻塞源',
        'auto_fixable': True,
        'auto_fix_method': 'kill_blockers',
        'references': [],
    },
    {
        'item_id': 'INS-COM-OPEN-CURSOR',
        'title': '打开游标数',
        'category': 'performance',
        'level': 'daily',
        'severity': 'info',
        'applicable_db_types': ['oracle', 'dm'],
        'description': '当前打开的游标数',
        'detect_method': 'detect_open_cursors',
        'threshold': {'warn': 1000, 'error': 5000, 'critical': 10000},
        'recommendation': '检查应用游标泄漏',
        'auto_fixable': False,
        'references': [],
    },
    {
        'item_id': 'INS-COM-TEMP-USAGE',
        'title': '临时表空间使用',
        'category': 'capacity',
        'level': 'daily',
        'severity': 'warn',
        'applicable_db_types': ['oracle', 'mysql', 'pgsql', 'dm', 'gbase'],
        'description': '临时表空间使用率',
        'detect_method': 'detect_temp_usage',
        'threshold': {'warn': 70, 'error': 85, 'critical': 95},
        'recommendation': '扩容临时表空间或优化大排序',
        'auto_fixable': True,
        'auto_fix_method': 'resize_temp_tablespace',
        'references': [],
    },
    {
        'item_id': 'INS-COM-UNDO-USAGE',
        'title': 'Undo 使用率',
        'category': 'capacity',
        'level': 'daily',
        'severity': 'warn',
        'applicable_db_types': ['oracle', 'dm', 'pgsql'],
        'description': 'Undo 表空间使用率',
        'detect_method': 'detect_undo_usage',
        'threshold': {'warn': 70, 'error': 85, 'critical': 95},
        'recommendation': '扩容 undo 或排查长事务',
        'auto_fixable': True,
        'auto_fix_method': 'resize_undo',
        'references': [],
    },
    {
        'item_id': 'INS-COM-FRAG-TABLE',
        'title': '高并行度表',
        'category': 'object',
        'level': 'monthly',
        'severity': 'info',
        'applicable_db_types': ['oracle', 'dm', 'gbase'],
        'description': '设置了过高并行度的表',
        'detect_method': 'detect_high_parallel',
        'threshold': {'warn': 1, 'error': 5, 'critical': 10},
        'recommendation': '评估并行度是否合理',
        'auto_fixable': False,
        'references': [],
    },
    {
        'item_id': 'INS-COM-FAILED-LOGIN',
        'title': '失败登录异常',
        'category': 'security',
        'level': 'daily',
        'severity': 'warn',
        'applicable_db_types': ['oracle', 'mysql', 'pgsql', 'dm'],
        'description': '24h 失败登录次数',
        'detect_method': 'detect_failed_logins',
        'threshold': {'warn': 50, 'error': 200, 'critical': 1000},
        'recommendation': '审计源 IP,检查是否被攻击',
        'auto_fixable': False,
        'references': [],
    },
]


# ==========================================
# Oracle 专项巡检 (30 项)
# ==========================================
ORACLE_ITEMS: List[Dict[str, Any]] = [
    {
        'item_id': 'INS-ORA-AWR-SNAP',
        'title': 'AWR 快照间隔',
        'category': 'awr',
        'level': 'weekly',
        'severity': 'warn',
        'applicable_db_types': ['oracle'],
        'description': 'AWR 快照采集间隔是否合理',
        'detect_method': 'detect_awr_interval',
        'threshold': {'warn': 60, 'error': 120, 'critical': 240},
        'recommendation': '建议 15-60 分钟',
        'auto_fixable': True,
        'auto_fix_method': 'set_awr_interval',
    },
    {
        'item_id': 'INS-ORA-AWR-RET',
        'title': 'AWR 保留周期',
        'category': 'awr',
        'level': 'monthly',
        'severity': 'warn',
        'applicable_db_types': ['oracle'],
        'description': 'AWR 数据保留天数',
        'detect_method': 'detect_awr_retention',
        'threshold': {'warn': 30, 'error': 14, 'critical': 7},
        'recommendation': '建议保留 ≥ 30 天',
        'auto_fixable': True,
        'auto_fix_method': 'set_awr_retention',
    },
    {
        'item_id': 'INS-ORA-AWR-TOP-EVT',
        'title': '业务高峰 Top Event',
        'category': 'awr',
        'level': 'weekly',
        'severity': 'info',
        'applicable_db_types': ['oracle'],
        'description': '业务高峰时段的 Top 等待事件',
        'detect_method': 'detect_awr_top_event',
        'threshold': {'warn': 1, 'error': 5, 'critical': 10},
        'recommendation': '分析等待事件,优化 SQL/参数',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-AWR-TOP-SQL',
        'title': '业务高峰 Top SQL',
        'category': 'awr',
        'level': 'weekly',
        'severity': 'info',
        'applicable_db_types': ['oracle'],
        'description': '业务高峰时段消耗 Top SQL',
        'detect_method': 'detect_awr_top_sql',
        'threshold': {'warn': 1, 'error': 5, 'critical': 10},
        'recommendation': '优化 Top SQL',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-SCN-HEADROOM',
        'title': 'SCN Headroom',
        'category': 'awr',
        'level': 'daily',
        'severity': 'critical',
        'applicable_db_types': ['oracle'],
        'description': '距离 SCN 极限的天数',
        'detect_method': 'detect_scn_headroom',
        'threshold': {'warn': 180, 'error': 90, 'critical': 30},
        'recommendation': '高并发 commit 会消耗 SCN,需控制速率',
        'auto_fixable': False,
        'references': ['Oracle MOS 2335265.1'],
    },
    {
        'item_id': 'INS-ORA-STA-OUTPUT',
        'title': 'SQL Tuning Advisor 结果',
        'category': 'task',
        'level': 'weekly',
        'severity': 'info',
        'applicable_db_types': ['oracle'],
        'description': 'STA 任务的最新建议',
        'detect_method': 'detect_sta_recommendations',
        'threshold': {'warn': 1, 'error': 10, 'critical': 50},
        'recommendation': '执行 STA 推荐 SQL',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-SEG-ADV',
        'title': 'Segment Advisor 结果',
        'category': 'task',
        'level': 'weekly',
        'severity': 'info',
        'applicable_db_types': ['oracle'],
        'description': 'Segment Advisor 推荐的 shrink 段',
        'detect_method': 'detect_segment_advisor',
        'threshold': {'warn': 1, 'error': 10, 'critical': 50},
        'recommendation': '执行 shrink segment',
        'auto_fixable': True,
        'auto_fix_method': 'shrink_segments',
    },
    {
        'item_id': 'INS-ORA-AUTO-MW',
        'title': '自动维护窗口',
        'category': 'task',
        'level': 'monthly',
        'severity': 'info',
        'applicable_db_types': ['oracle'],
        'description': 'Maintenance Window 时长是否合理',
        'detect_method': 'detect_maintenance_window',
        'threshold': {'warn': 1, 'error': 2, 'critical': 3},
        'recommendation': '建议调整到业务低峰期',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-FRA',
        'title': 'FRA 使用率',
        'category': 'capacity',
        'level': 'daily',
        'severity': 'warn',
        'applicable_db_types': ['oracle'],
        'description': '快速恢复区使用率',
        'detect_method': 'detect_fra_usage',
        'threshold': {'warn': 70, 'error': 85, 'critical': 95},
        'recommendation': '备份归档并删除,扩容 FRA',
        'auto_fixable': True,
        'auto_fix_method': 'cleanup_fra',
    },
    {
        'item_id': 'INS-ORA-CTRL-BAK',
        'title': '控制文件备份',
        'category': 'operations',
        'level': 'weekly',
        'severity': 'warn',
        'applicable_db_types': ['oracle'],
        'description': '控制文件自动备份',
        'detect_method': 'detect_ctrlfile_backup',
        'threshold': {'warn': 1, 'error': 3, 'critical': 7},
        'recommendation': '检查 RMAN 配置',
        'auto_fixable': True,
        'auto_fix_method': 'enable_ctrlfile_autobackup',
    },
    {
        'item_id': 'INS-ORA-ARCH-DELETE',
        'title': '归档日志清理策略',
        'category': 'operations',
        'level': 'weekly',
        'severity': 'warn',
        'applicable_db_types': ['oracle'],
        'description': '归档日志是否配置自动清理',
        'detect_method': 'detect_arch_deletion_policy',
        'threshold': {'warn': 1, 'error': 2, 'critical': 3},
        'recommendation': '配置 RMAN ARCHIVELOG DELETION POLICY',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-DBA-USERS',
        'title': 'DBA 权限账号',
        'category': 'security',
        'level': 'monthly',
        'severity': 'warn',
        'applicable_db_types': ['oracle'],
        'description': 'DBA 权限账号数量',
        'detect_method': 'detect_dba_users',
        'threshold': {'warn': 10, 'error': 20, 'critical': 50},
        'recommendation': '回收非必要 DBA 权限',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-TS-AUTOEXT',
        'title': '表空间自动扩展',
        'category': 'config',
        'level': 'monthly',
        'severity': 'info',
        'applicable_db_types': ['oracle', 'dm'],
        'description': '关键表空间未启用自动扩展',
        'detect_method': 'detect_ts_autoextend',
        'threshold': {'warn': 1, 'error': 3, 'critical': 10},
        'recommendation': '为关键业务表空间启用自动扩展',
        'auto_fixable': True,
        'auto_fix_method': 'enable_autoextend',
    },
    {
        'item_id': 'INS-ORA-LOB-PCT',
        'title': 'LOB PCTVERSION 异常',
        'category': 'object',
        'level': 'monthly',
        'severity': 'warn',
        'applicable_db_types': ['oracle'],
        'description': 'LOB 列 PCTVERSION 设置过大',
        'detect_method': 'detect_lob_pctversion',
        'threshold': {'warn': 1, 'error': 5, 'critical': 20},
        'recommendation': '调整为合理值(默认 10)',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-DBLINK',
        'title': '残留 DBLINK',
        'category': 'object',
        'level': 'monthly',
        'severity': 'info',
        'applicable_db_types': ['oracle'],
        'description': '未使用的 DBLINK',
        'detect_method': 'detect_dblinks',
        'threshold': {'warn': 10, 'error': 30, 'critical': 100},
        'recommendation': '清理未使用的 DBLINK',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-DIR-OBJ',
        'title': 'Directory 对象',
        'category': 'security',
        'level': 'monthly',
        'severity': 'warn',
        'applicable_db_types': ['oracle'],
        'description': '异常 Directory 对象',
        'detect_method': 'detect_directory_objects',
        'threshold': {'warn': 5, 'error': 20, 'critical': 50},
        'recommendation': '清理异常目录',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-RMAN-AGE',
        'title': 'RMAN 备份距今',
        'category': 'operations',
        'level': 'daily',
        'severity': 'error',
        'applicable_db_types': ['oracle'],
        'description': '最近一次 RMAN 完整备份距今小时数',
        'detect_method': 'detect_rman_backup_age',
        'threshold': {'warn': 24, 'error': 48, 'critical': 72},
        'recommendation': '检查 RMAN 备份策略',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-DG-LAG',
        'title': 'DataGuard Lag',
        'category': 'replication',
        'level': 'daily',
        'severity': 'error',
        'applicable_db_types': ['oracle'],
        'description': 'DataGuard 备库 apply lag',
        'detect_method': 'detect_dg_lag',
        'threshold': {'warn': 30, 'error': 300, 'critical': 1800},
        'recommendation': '检查 redo 应用',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-DG-STATUS',
        'title': 'DataGuard 状态',
        'category': 'replication',
        'level': 'daily',
        'severity': 'critical',
        'applicable_db_types': ['oracle'],
        'description': 'DataGuard 整体状态',
        'detect_method': 'detect_dg_status',
        'threshold': {'warn': 1, 'error': 2, 'critical': 3},
        'recommendation': '立即人工干预',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-RAC-VIP',
        'title': 'RAC VIP 状态',
        'category': 'cluster',
        'level': 'daily',
        'severity': 'error',
        'applicable_db_types': ['oracle'],
        'description': 'RAC VIP 漂移状态',
        'detect_method': 'detect_rac_vip',
        'threshold': {'warn': 1, 'error': 2, 'critical': 3},
        'recommendation': '检查 oifcfg 和 vip 配置',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-REDOLOG-SIZE',
        'title': 'Redo Log 大小',
        'category': 'config',
        'level': 'monthly',
        'severity': 'warn',
        'applicable_db_types': ['oracle'],
        'description': 'Redo log 单文件大小',
        'detect_method': 'detect_redolog_size',
        'threshold': {'warn': 1024, 'error': 512, 'critical': 200},
        'recommendation': '建议 ≥ 1GB,减少切换频率',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-OPT-STATS-GATHER',
        'title': '自动统计信息收集',
        'category': 'statistics',
        'level': 'weekly',
        'severity': 'warn',
        'applicable_db_types': ['oracle'],
        'description': '自动统计信息任务状态',
        'detect_method': 'detect_auto_stats_gather',
        'threshold': {'warn': 1, 'error': 2, 'critical': 3},
        'recommendation': '检查 auto stats job',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-OPEN-FILE',
        'title': '打开文件数',
        'category': 'performance',
        'level': 'daily',
        'severity': 'warn',
        'applicable_db_types': ['oracle'],
        'description': '数据库打开的文件数',
        'detect_method': 'detect_open_files',
        'threshold': {'warn': 10000, 'error': 30000, 'critical': 60000},
        'recommendation': '检查文件描述符',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-LOB-CACHE',
        'title': 'LOB CACHE 读取',
        'category': 'performance',
        'level': 'monthly',
        'severity': 'info',
        'applicable_db_types': ['oracle'],
        'description': 'LOB Cache 命中率',
        'detect_method': 'detect_lob_cache_hit',
        'threshold': {'warn': 50, 'error': 30, 'critical': 10},
        'recommendation': '考虑开启 CACHE=READ',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-ASH-USAGE',
        'title': 'ASH 内存使用',
        'category': 'awr',
        'level': 'monthly',
        'severity': 'info',
        'applicable_db_types': ['oracle'],
        'description': 'ASH buffer 内存使用',
        'detect_method': 'detect_ash_memory',
        'threshold': {'warn': 80, 'error': 90, 'critical': 95},
        'recommendation': '调整 _ash_size',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-RMAN-CONF',
        'title': 'RMAN 配置',
        'category': 'config',
        'level': 'monthly',
        'severity': 'info',
        'applicable_db_types': ['oracle'],
        'description': 'RMAN 备份保留策略和优化',
        'detect_method': 'detect_rman_config',
        'threshold': {'warn': 1, 'error': 3, 'critical': 5},
        'recommendation': '运行 RMAN 配置检查',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-AUDIT-TRAIL',
        'title': '审计日志',
        'category': 'security',
        'level': 'weekly',
        'severity': 'warn',
        'applicable_db_types': ['oracle'],
        'description': '审计日志是否启用',
        'detect_method': 'detect_audit_trail',
        'threshold': {'warn': 1, 'error': 2, 'critical': 3},
        'recommendation': '配置 audit_trail=DB',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-PGA-LEAK',
        'title': 'PGA 泄漏',
        'category': 'memory',
        'level': 'monthly',
        'severity': 'warn',
        'applicable_db_types': ['oracle'],
        'description': 'PGA 实际分配超 target',
        'detect_method': 'detect_pga_leak',
        'threshold': {'warn': 80, 'error': 95, 'critical': 110},
        'recommendation': '排查异常会话',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-IO-STAT',
        'title': 'IO 分布',
        'category': 'performance',
        'level': 'monthly',
        'severity': 'info',
        'applicable_db_types': ['oracle'],
        'description': '数据文件 IO 分布',
        'detect_method': 'detect_io_distribution',
        'threshold': {'warn': 1, 'error': 5, 'critical': 10},
        'recommendation': '热点文件优化',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-ORA-EXADATA',
        'title': 'Exadata 特性',
        'category': 'config',
        'level': 'monthly',
        'severity': 'info',
        'applicable_db_types': ['oracle'],
        'description': 'Exadata 智能扫描等特性',
        'detect_method': 'detect_exadata_features',
        'threshold': {'warn': 1, 'error': 3, 'critical': 5},
        'recommendation': '检查 cell_offload',
        'auto_fixable': False,
    },
]


# ==========================================
# MySQL 专项 (6 项)
# ==========================================
MYSQL_ITEMS: List[Dict[str, Any]] = [
    {
        'item_id': 'INS-MYSQL-BINLOG-DELAY',
        'title': 'Binlog Dump 延迟',
        'category': 'replication',
        'level': 'daily',
        'severity': 'warn',
        'applicable_db_types': ['mysql', 'tdsql'],
        'description': 'Binlog dump 线程延迟',
        'detect_method': 'detect_binlog_dump_delay',
        'threshold': {'warn': 10, 'error': 60, 'critical': 300},
        'recommendation': '检查网络和主库写入',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-MYSQL-GTID',
        'title': 'GTID 一致性',
        'category': 'replication',
        'level': 'weekly',
        'severity': 'warn',
        'applicable_db_types': ['mysql', 'tdsql'],
        'description': '主从 GTID 是否一致',
        'detect_method': 'detect_gtid_consistency',
        'threshold': {'warn': 1, 'error': 3, 'critical': 5},
        'recommendation': '检查主从异常',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-MYSQL-SEMI-SYNC',
        'title': '半同步复制状态',
        'category': 'replication',
        'level': 'daily',
        'severity': 'warn',
        'applicable_db_types': ['mysql', 'tdsql'],
        'description': '半同步是否生效',
        'detect_method': 'detect_semi_sync',
        'threshold': {'warn': 1, 'error': 2, 'critical': 3},
        'recommendation': '检查 rpl_semi_sync_master_wait',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-MYSQL-EVENT',
        'title': 'Event 调度器',
        'category': 'task',
        'level': 'weekly',
        'severity': 'info',
        'applicable_db_types': ['mysql', 'tdsql'],
        'description': 'Event Scheduler 是否开启',
        'detect_method': 'detect_event_scheduler',
        'threshold': {'warn': 1, 'error': 2, 'critical': 3},
        'recommendation': '确保 event_scheduler=ON',
        'auto_fixable': True,
        'auto_fix_method': 'enable_event_scheduler',
    },
    {
        'item_id': 'INS-MYSQL-FK-CASCADE',
        'title': '危险外键级联',
        'category': 'config',
        'level': 'monthly',
        'severity': 'warn',
        'applicable_db_types': ['mysql', 'tdsql'],
        'description': '外键 ON DELETE CASCADE',
        'detect_method': 'detect_dangerous_fk',
        'threshold': {'warn': 5, 'error': 20, 'critical': 50},
        'recommendation': '业务层控制删除',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-MYSQL-TMP-DISK',
        'title': '磁盘临时表比例',
        'category': 'performance',
        'level': 'daily',
        'severity': 'warn',
        'applicable_db_types': ['mysql', 'tdsql'],
        'description': 'Created_tmp_disk_tables / total',
        'detect_method': 'detect_tmp_disk_ratio',
        'threshold': {'warn': 25, 'error': 50, 'critical': 75},
        'recommendation': '调大 tmp_table_size',
        'auto_fixable': False,
    },
]


# ==========================================
# PostgreSQL 专项 (6 项)
# ==========================================
PGSQL_ITEMS: List[Dict[str, Any]] = [
    {
        'item_id': 'INS-PG-WAL-RECV',
        'title': 'WAL Receiver 状态',
        'category': 'replication',
        'level': 'daily',
        'severity': 'warn',
        'applicable_db_types': ['pgsql'],
        'description': '从库 WAL 接收线程',
        'detect_method': 'detect_wal_receiver',
        'threshold': {'warn': 1, 'error': 2, 'critical': 3},
        'recommendation': '检查流复制配置',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-PG-INACTIVE-SLOT',
        'title': '失效复制槽',
        'category': 'replication',
        'level': 'daily',
        'severity': 'error',
        'applicable_db_types': ['pgsql'],
        'description': 'inactive 状态的复制槽',
        'detect_method': 'detect_inactive_repl_slot',
        'threshold': {'warn': 1, 'error': 3, 'critical': 5},
        'recommendation': '清理无效 slot 否则 WAL 撑爆',
        'auto_fixable': True,
        'auto_fix_method': 'drop_inactive_slots',
    },
    {
        'item_id': 'INS-PG-VACUUM-FREEZE',
        'title': 'Freeze Age',
        'category': 'statistics',
        'level': 'daily',
        'severity': 'critical',
        'applicable_db_types': ['pgsql'],
        'description': '表 age 接近 2亿',
        'detect_method': 'detect_freeze_age',
        'threshold': {'warn': 100000000, 'error': 180000000, 'critical': 200000000},
        'recommendation': '紧急 VACUUM FREEZE',
        'auto_fixable': True,
        'auto_fix_method': 'vacuum_freeze',
    },
    {
        'item_id': 'INS-PG-BLOAT',
        'title': '表/索引膨胀',
        'category': 'statistics',
        'level': 'weekly',
        'severity': 'warn',
        'applicable_db_types': ['pgsql'],
        'description': '膨胀率超过 50% 的对象',
        'detect_method': 'detect_bloat',
        'threshold': {'warn': 5, 'error': 20, 'critical': 50},
        'recommendation': 'VACUUM FULL / REINDEX',
        'auto_fixable': True,
        'auto_fix_method': 'vacuum_full_bloat',
    },
    {
        'item_id': 'INS-PG-EXT-OUTDATED',
        'title': '扩展版本',
        'category': 'config',
        'level': 'monthly',
        'severity': 'info',
        'applicable_db_types': ['pgsql'],
        'description': '已安装扩展的版本',
        'detect_method': 'detect_extension_versions',
        'threshold': {'warn': 1, 'error': 3, 'critical': 5},
        'recommendation': '升级扩展',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-PG-STMT-TIMEOUT',
        'title': 'Statement Timeout',
        'category': 'config',
        'level': 'monthly',
        'severity': 'info',
        'applicable_db_types': ['pgsql'],
        'description': '应用层 statement_timeout',
        'detect_method': 'detect_statement_timeout',
        'threshold': {'warn': 1, 'error': 2, 'critical': 3},
        'recommendation': '建议应用层设置超时',
        'auto_fixable': False,
    },
]


# ==========================================
# 达梦 DM 专项 (4 项)
# ==========================================
DM_ITEMS: List[Dict[str, Any]] = [
    {
        'item_id': 'INS-DM-DSC',
        'title': 'DSC 节点状态',
        'category': 'cluster',
        'level': 'daily',
        'severity': 'error',
        'applicable_db_types': ['dm'],
        'description': 'DSC 集群节点状态',
        'detect_method': 'detect_dsc_nodes',
        'threshold': {'warn': 1, 'error': 2, 'critical': 3},
        'recommendation': '检查 DMCSS 日志',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-DM-DW-STANDBY',
        'title': '主备同步状态',
        'category': 'replication',
        'level': 'daily',
        'severity': 'error',
        'applicable_db_types': ['dm'],
        'description': 'DataWatch 主备同步',
        'detect_method': 'detect_dw_standby',
        'threshold': {'warn': 1, 'error': 2, 'critical': 3},
        'recommendation': '检查 DMWATCHER',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-DM-ARCH',
        'title': '归档状态',
        'category': 'log',
        'level': 'daily',
        'severity': 'warn',
        'applicable_db_types': ['dm'],
        'description': '归档是否正常',
        'detect_method': 'detect_dm_arch',
        'threshold': {'warn': 1, 'error': 2, 'critical': 3},
        'recommendation': '检查归档目录',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-DM-RLOG',
        'title': 'RLOG 同步状态',
        'category': 'replication',
        'level': 'daily',
        'severity': 'warn',
        'applicable_db_types': ['dm'],
        'description': 'RLOG 实时同步',
        'detect_method': 'detect_dm_rlog',
        'threshold': {'warn': 1, 'error': 2, 'critical': 3},
        'recommendation': '检查 RLOG_PKG',
        'auto_fixable': False,
    },
]


# ==========================================
# GBase 8A 专项 (3 项)
# ==========================================
GBASE_ITEMS: List[Dict[str, Any]] = [
    {
        'item_id': 'INS-GBASE-BALANCE',
        'title': '节点负载均衡',
        'category': 'cluster',
        'level': 'daily',
        'severity': 'warn',
        'applicable_db_types': ['gbase'],
        'description': '集群节点负载偏差',
        'detect_method': 'detect_gbase_node_balance',
        'threshold': {'warn': 30, 'error': 50, 'critical': 80},
        'recommendation': 'rebalance 集群',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-GBASE-DIST',
        'title': '数据分布均衡',
        'category': 'cluster',
        'level': 'weekly',
        'severity': 'warn',
        'applicable_db_types': ['gbase'],
        'description': '数据分布偏差',
        'detect_method': 'detect_gbase_distribution',
        'threshold': {'warn': 30, 'error': 50, 'critical': 80},
        'recommendation': '调整分布策略',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-GBASE-NODE-DOWN',
        'title': '节点宕机',
        'category': 'cluster',
        'level': 'daily',
        'severity': 'critical',
        'applicable_db_types': ['gbase'],
        'description': '集群节点宕机',
        'detect_method': 'detect_gbase_node_down',
        'threshold': {'warn': 1, 'error': 2, 'critical': 3},
        'recommendation': '立即人工干预',
        'auto_fixable': False,
    },
]


# ==========================================
# TDSQL 专项 (3 项)
# ==========================================
TDSQL_ITEMS: List[Dict[str, Any]] = [
    {
        'item_id': 'INS-TDSQL-SHARD',
        'title': '分片状态',
        'category': 'cluster',
        'level': 'daily',
        'severity': 'error',
        'applicable_db_types': ['tdsql'],
        'description': 'TDSQL 分片健康状态',
        'detect_method': 'detect_tdsql_shard',
        'threshold': {'warn': 1, 'error': 2, 'critical': 3},
        'recommendation': '检查 proxy 和 shard',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-TDSQL-PROXY',
        'title': 'Proxy 状态',
        'category': 'cluster',
        'level': 'daily',
        'severity': 'error',
        'applicable_db_types': ['tdsql'],
        'description': 'TDSQL Proxy 节点',
        'detect_method': 'detect_tdsql_proxy',
        'threshold': {'warn': 1, 'error': 2, 'critical': 3},
        'recommendation': '检查 proxy 进程',
        'auto_fixable': False,
    },
    {
        'item_id': 'INS-TDSQL-ZK',
        'title': 'ZK 状态',
        'category': 'cluster',
        'level': 'daily',
        'severity': 'error',
        'applicable_db_types': ['tdsql'],
        'description': 'ZooKeeper 集群',
        'detect_method': 'detect_tdsql_zk',
        'threshold': {'warn': 1, 'error': 2, 'critical': 3},
        'recommendation': '检查 zk 集群',
        'auto_fixable': False,
    },
]


# 汇总
ALL_ITEMS = COMMON_ITEMS + ORACLE_ITEMS + MYSQL_ITEMS + PGSQL_ITEMS + DM_ITEMS + GBASE_ITEMS + TDSQL_ITEMS


def get_total_count() -> int:
    return len(ALL_ITEMS)


def get_count_by_level() -> Dict[str, int]:
    result = {}
    for it in ALL_ITEMS:
        level = it['level']
        result[level] = result.get(level, 0) + 1
    return result


def get_count_by_db_type() -> Dict[str, int]:
    result = {}
    for it in ALL_ITEMS:
        for db in it.get('applicable_db_types', []):
            result[db] = result.get(db, 0) + 1
    return result
